import type { Effect } from "effect";
import type * as Compiler from "@relkit/compiler";
import type { CliAdapterError } from "../cli-errors.js";

/**
 * Adapts one installed compiler declaration without widening arguments or results.
 * @typeParam F - Exact compiler API declaration.
 */
type CompilerCall<F extends (...args: never[]) => unknown> = (
  ...args: Parameters<F>
) => Effect.Effect<Awaited<ReturnType<F>>, CliAdapterError>;

/** Native compiler authority; pure graph transforms stay with their owning library. */
export interface CompilerCapabilities {
  /**
   * Validates/defaults imported tooling configuration without application execution.
   * @param args - Configuration value, project root and owner validation options.
   * @returns Accepted full tooling configuration or original validation failure.
   */
  readonly loadConfig: CompilerCall<typeof Compiler.loadConfig>;
  /**
   * Evaluates authored descriptors in the compiler's scoped isolated evaluator.
   * @param args - Selected sources, generation identity and evaluator policy.
   * @returns Owner-validated descriptor/source evidence after evaluator cleanup.
   */
  readonly evaluate: CompilerCall<typeof Compiler.evaluateCandidates>;
  /**
   * Checks the authored project using the installed compiler's diagnostic policy.
   * @param args - Root, source policy and compiler options.
   * @returns Ordinary deterministic TypeScript diagnostics.
   */
  readonly typecheck: CompilerCall<typeof Compiler.typecheckProject>;
  /**
   * Resolves one contained integration role without importing package code.
   * @param args - Exact package, identity, role and resolution root.
   * @returns Validated package/version/export metadata.
   */
  readonly integrationRole: CompilerCall<typeof Compiler.resolveIntegrationPackageRole>;
  /**
   * Resolves all runtime integration declarations required by accepted graph input.
   * @param args - Normalized graph inputs and package resolution root.
   * @returns Compiler-owned runtime integration package evidence.
   */
  readonly integrationPackages: CompilerCall<typeof Compiler.resolveRuntimeIntegrationPackages>;
  /**
   * Writes generated bytes only when content differs.
   * @param args - Accepted destination and complete generated text.
   * @returns Owner write evidence after native mutation settles.
   */
  readonly writeChanged: CompilerCall<typeof Compiler.writeIfChanged>;
  /**
   * Publishes the accepted generated artifact cohort under compiler ownership.
   * @param args - Complete outputs and generated directory policy.
   * @returns Per-artifact write/unchanged evidence.
   */
  readonly writeArtifacts: CompilerCall<typeof Compiler.writeGeneratedArtifacts>;
  /**
   * Emits the selected job worker entries with captured storage authority.
   * @param args - Accepted jobs manifest and compiler-owned worker paths.
   * @returns Worker artifact write evidence after completion.
   */
  readonly writeWorkers: CompilerCall<typeof Compiler.writeJobWorkerEntries>;
}
