import {
  LOCAL_SERVICE_RECIPE_PROTOCOL_VERSION,
  type CompositeLocalServiceRecipe,
  type LocalServiceRecipeOutputContext,
} from "@relkit/local-service";
import { BUN_IMAGE, number, POSTGRES_IMAGE, text } from "./local-support.js";
const EFFECT_MQ_SCHEMA_SQL = String.raw`
CREATE TABLE IF NOT EXISTS effect_mq (
  id text PRIMARY KEY,
  name text NOT NULL,
  queue text NOT NULL,
  state text NOT NULL,
  priority integer NOT NULL DEFAULT 0,
  seq bigint GENERATED BY DEFAULT AS IDENTITY,
  payload jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  attempts_max integer NOT NULL,
  attempts_made integer NOT NULL DEFAULT 0,
  stalled_count integer NOT NULL DEFAULT 0,
  backoff jsonb,
  keep jsonb,
  timeout_ms bigint,
  cancel_requested boolean NOT NULL DEFAULT false,
  dedupe_key text,
  trace jsonb,
  parent jsonb,
  flow_fail_fast boolean,
  flow_pending integer,
  flow_completed integer,
  flow_failed integer,
  flow_cancelled integer,
  run_at timestamptz NOT NULL,
  enqueued_at timestamptz NOT NULL,
  processed_at timestamptz,
  finished_at timestamptz,
  exit jsonb,
  failed_reason text,
  lock_token text,
  lock_expires_at timestamptz
);
CREATE INDEX IF NOT EXISTS effect_mq_ready_idx ON effect_mq (queue, priority DESC, seq ASC) WHERE state = 'waiting';
CREATE INDEX IF NOT EXISTS effect_mq_delayed_idx ON effect_mq (queue, run_at) WHERE state = 'delayed';
CREATE INDEX IF NOT EXISTS effect_mq_active_idx ON effect_mq (lock_expires_at) WHERE state = 'active';
CREATE INDEX IF NOT EXISTS effect_mq_history_idx ON effect_mq (name, state, finished_at);
CREATE INDEX IF NOT EXISTS effect_mq_listing_idx ON effect_mq (enqueued_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS effect_mq_metadata_idx ON effect_mq USING gin (metadata jsonb_path_ops);
CREATE TABLE IF NOT EXISTS effect_mq_job_attempts (
  job_id text NOT NULL REFERENCES effect_mq (id) ON DELETE CASCADE,
  attempt integer NOT NULL,
  outcome text NOT NULL,
  started_at timestamptz,
  finished_at timestamptz NOT NULL,
  exit jsonb,
  PRIMARY KEY (job_id, attempt)
);
CREATE TABLE IF NOT EXISTS effect_mq_schedules (
  key text PRIMARY KEY,
  job_name text NOT NULL,
  queue text NOT NULL,
  cron text,
  tz text,
  every_ms bigint,
  payload jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  priority integer NOT NULL DEFAULT 0,
  attempts_max integer NOT NULL,
  backoff jsonb,
  keep jsonb,
  timeout_ms bigint,
  group_name text,
  next_run_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS effect_mq_schedules_due_idx ON effect_mq_schedules (next_run_at);
CREATE TABLE IF NOT EXISTS effect_mq_queue_control (
  queue text PRIMARY KEY,
  paused boolean NOT NULL DEFAULT false
);
CREATE TABLE IF NOT EXISTS effect_mq_dedupe (
  name text NOT NULL,
  key text NOT NULL,
  job_id text NOT NULL,
  window_expires_at timestamptz,
  PRIMARY KEY (name, key)
);
CREATE TABLE IF NOT EXISTS effect_mq_flow_children (
  flow_id text NOT NULL,
  child_key text NOT NULL,
  name text NOT NULL,
  store_key text NOT NULL,
  spec jsonb NOT NULL,
  status text NOT NULL,
  exit jsonb,
  failed_reason text,
  cascaded boolean NOT NULL,
  pending_since timestamptz NOT NULL,
  PRIMARY KEY (flow_id, child_key)
);
CREATE INDEX IF NOT EXISTS effect_mq_flow_children_pending_idx ON effect_mq_flow_children (pending_since) WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS effect_mq_flow_children_cascade_idx ON effect_mq_flow_children (flow_id) WHERE status = 'cancelled' AND NOT cascaded;
CREATE TABLE IF NOT EXISTS effect_mq_flow_outbox (
  id bigserial PRIMARY KEY,
  flow_name text NOT NULL,
  parent_store_key text NOT NULL,
  report jsonb NOT NULL
);`;
const EFFECT_MQ_SCHEMA_COMMAND = EFFECT_MQ_SCHEMA_SQL.replace(/\s+/gu, " ").trim();

export const localRecipe = Object.freeze({
  kind: "local-service-recipe",
  protocolVersion: LOCAL_SERVICE_RECIPE_PROTOCOL_VERSION,
  integrationId: "effect-mq",
  recipeId: "effect-mq-docker",
  recipeVersion: 2,
  materializerId: "docker",
  containers: Object.freeze([
    Object.freeze({
      id: "postgres",
      image: POSTGRES_IMAGE,
      ports: Object.freeze({ postgres: 5432 }),
      volumes: Object.freeze([{ name: "postgres", mountPath: "/var/lib/postgresql/data" }]),
      environment: Object.freeze({
        POSTGRES_DB: Object.freeze({ value: "relkit" }),
        POSTGRES_USER: Object.freeze({ value: "relkit" }),
        POSTGRES_PASSWORD: Object.freeze({ secret: "postgresPassword" }),
      }),
      health: Object.freeze({
        command: ["pg_isready", "-U", "relkit", "-d", "relkit"],
        intervalMs: 250,
        timeoutMs: 2_000,
        retries: 60,
      }),
      networkAliases: Object.freeze(["postgres"]),
    }),
  ]),
  init: Object.freeze([
    Object.freeze({
      id: "postgres-ready",
      image: POSTGRES_IMAGE,
      dependsOn: Object.freeze(["postgres"]),
      command: Object.freeze([
        "sh",
        "-c",
        "until PGPASSWORD=$POSTGRES_PASSWORD psql -h postgres -U relkit -d relkit -c 'select 1' >/dev/null 2>&1; do sleep 1; done; " +
          `PGPASSWORD=$POSTGRES_PASSWORD psql -v ON_ERROR_STOP=1 -h postgres -U relkit -d relkit -c "${EFFECT_MQ_SCHEMA_COMMAND}"`,
      ]),
      environment: Object.freeze({
        POSTGRES_PASSWORD: Object.freeze({ secret: "postgresPassword" }),
      }),
    }),
  ]),
  workers: Object.freeze([
    Object.freeze({
      id: "worker",
      image: BUN_IMAGE,
      command: Object.freeze([
        "bun",
        "run",
        "--no-env-file",
        "--no-install",
        "/relkit-worker/server/index.js",
      ]),
      dependsOn: Object.freeze(["postgres-ready"]),
      ports: Object.freeze({ api: 3000 }),
      health: Object.freeze({
        command: ["kill", "-0", "1"],
        intervalMs: 500,
        timeoutMs: 2_000,
        retries: 120,
      }),
      networkAliases: Object.freeze(["worker"]),
      hostAliases: Object.freeze({ "host.docker.internal": "host-gateway" }),
      environment: Object.freeze({
        RELKIT_EFFECT_MQ_DATABASE_URL: Object.freeze({
          value: "postgres://relkit:$POSTGRES_PASSWORD@postgres:5432/relkit",
        }),
        RELKIT_EFFECT_MQ_MIGRATIONS: Object.freeze({ value: "owned-by-jobs-service" }),
      }),
    }),
  ]),
  volumes: Object.freeze({
    postgres: Object.freeze({ mountPath: "/var/lib/postgresql/data", persistent: true }),
  }),
  generatedSecrets: Object.freeze({
    postgresPassword: Object.freeze({ bytes: 24, encoding: "hex" }),
  }),
  network: Object.freeze({ internal: false }),
  ownership: Object.freeze({ scope: "project", retainVolumes: true }),
  outputs: ({ ports, secrets }: LocalServiceRecipeOutputContext) =>
    Object.freeze({
      postgresUrl:
        "postgres://relkit:" +
        text(secrets.postgresPassword, "postgres password") +
        "@127.0.0.1:" +
        number(ports.postgres, "Effect MQ PostgreSQL port") +
        "/relkit",
    }),
}) satisfies CompositeLocalServiceRecipe<"effect-mq">;
