FROM oven/bun:1.3.10 AS bun

FROM node:24-bookworm-slim

COPY --from=bun /usr/local/bin/bun /usr/local/bin/bun

WORKDIR /app

COPY . .
RUN bun install --frozen-lockfile
RUN bun x turbo run build --filter=@relkit/docs

EXPOSE 3000

CMD ["bun", "--cwd=apps/docs", "run", "start"]
