import * as agents from "@relkit/app/agents";
import * as buckets from "@relkit/app/buckets";
import * as cache from "@relkit/app/cache";
import * as config from "@relkit/app/config";
import * as events from "@relkit/app/events";
import * as functions from "@relkit/app/functions";
import * as jobs from "@relkit/app/jobs";
import * as routes from "@relkit/app/routes";
import * as schema from "@relkit/app/schema";
import * as services from "@relkit/app/services";
import * as tools from "@relkit/app/tools";

void agents.defineAgent;
void buckets.defineBucket;
void cache.defineCache;
void config.defineApp;
void config.defineEnv;
void config.projectEnv;
void events.defineEvent;
void functions.defineFunction;
void jobs.defineJob;
void routes.defineRoute;
void schema.z;
void services.defineService;
void tools.defineTool;
