import { expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { getCliHelpModel } from "@relkit/cli/help";
import { guideRelations } from "../scripts/guide-catalog.js";

test("every add command has a detailed guide, example, and complete generated option table", () => {
  const content = resolve(import.meta.dir, "../content");
  const model = getCliHelpModel("test");
  const add = model.commands.find(({ name }) => name === "add")!;
  const pages = guideRelations.map(({ path }) =>
    readFileSync(resolve(content, `docs/${path}.mdx`), "utf8"),
  );
  const index = readFileSync(resolve(content, "docs/start/add-artifacts.mdx"), "utf8");
  for (const command of add.commands) {
    const fragment = `add-${command.name}-options.mdx`;
    const guides = pages.filter((source) => source.includes(`content/generated/${fragment}`));
    expect(guides.length, command.name).toBeGreaterThan(0);
    expect(guides.some((source) => source.includes(`bun run relkit add ${command.name} `))).toBe(
      true,
    );
    expect(index).toContain(`relkit add ${command.name}`);
    const options = readFileSync(resolve(content, `generated/${fragment}`), "utf8");
    expect(options).toContain("Generated by apps/docs/scripts/generate.ts");
    for (const option of [...model.options, ...command.options])
      expect(options, `${command.name}: --${option.name}`).toContain(`"--${option.name}"`);
  }
});
