import { expect, test } from "bun:test";
import { readFile, readdir } from "node:fs/promises";
import { join, resolve } from "node:path";
import { features } from "../scripts/feature-catalog.js";
import {
  renderCapabilities,
  renderCreateOptions,
  renderRelated,
} from "../scripts/generate-guides.js";
import { guideGroups, guideRelations } from "../scripts/guide-catalog.js";
import { getCliHelpModel } from "@relkit/cli/help";

const content = resolve(import.meta.dir, "../content/docs");

test("publishes authored, CLI, and application-facing API documentation", async () => {
  const files = await markdownFiles(content);
  expect(files.length).toBeGreaterThanOrEqual(34);
  expect(await readFile(resolve(content, "operations/cli-reference.mdx"), "utf8")).toContain(
    "`relkit graph diff <before> <after>`",
  );
  for (const packageName of [
    "app",
    "config",
    "schema",
    "functions",
    "services",
    "drizzle",
    "better-auth",
    "routes",
    "events",
    "jobs",
    "buckets",
    "cache",
    "tools",
    "agents",
    "client",
    "testing",
  ]) {
    const reference = await readFile(resolve(content, `api/${packageName}.mdx`), "utf8");
    expect(reference).toContain("Generated by apps/docs/scripts/generate.ts");
    expect(reference).toContain("**Signature**");
  }
});

test("keeps guides backed by executable examples and self-hosted discovery", async () => {
  const files = await markdownFiles(content);
  const routes = await readFile(resolve(content, "http/routes.mdx"), "utf8");
  const events = await readFile(resolve(content, "async/events.mdx"), "utf8");
  const listeners = await readFile(resolve(content, "async/listeners.mdx"), "utf8");
  expect(routes).toContain("examples/commerce/src/routes/orders/[orderId]/route.ts");
  expect(events).toContain("templates/default/v1/api/src/orders/events/order-created.event.ts");
  expect(listeners).toContain(
    "templates/default/v1/api/src/orders/functions/order-confirmation.function.ts",
  );
  expect(await Bun.file(resolve(import.meta.dir, "../app/api/search/route.ts")).text()).toContain(
    "createFromSource(source)",
  );
  expect(await Bun.file(resolve(import.meta.dir, "../app/llms.txt/route.ts")).text()).toContain(
    "llms(source).index()",
  );

  for (const file of files.filter(
    (file) => !file.includes("/api/") && !file.endsWith("/operations/cli-reference.mdx"),
  )) {
    expect(await readFile(file, "utf8")).not.toMatch(/^\s*```(?:ts|tsx)\b/m);
  }

  for (const removedBundle of [
    "start/check-build-deploy.mdx",
    "fundamentals/schemas-errors-context.mdx",
    "http/uploads-middleware-rate-limits.mdx",
    "http/responses-openapi-clients.mdx",
    "resources-ai/buckets-cache.mdx",
    "resources-ai/tools-agents.mdx",
  ]) {
    expect(files).not.toContain(resolve(content, removedBundle));
  }
});

test("keeps current guidance on the domain-first application layout", async () => {
  const createPage = resolve(content, "start/create-an-app.mdx");
  const currentSources = [
    ...(await markdownFiles(content)).filter(
      (file) =>
        !file.includes("/api/") && !file.endsWith("/fundamentals/domain-first-migration.mdx"),
    ),
    resolve(import.meta.dir, "../components/landing/snippets.ts"),
    resolve(import.meta.dir, "../../../docs/getting-started.md"),
    resolve(import.meta.dir, "../../../docs/testing.md"),
  ];
  const legacyPath =
    /(?:^|[\s"'`(])(?:src\/(?:env\.ts|(?:functions|events|services|agents|jobs|cache|buckets|tools|middleware|transforms|shared)(?:\/|\b))|@app\/(?:functions|events|services|agents|jobs|cache|buckets|tools|middleware|transforms|shared)(?:\/|\b))/m;

  for (const file of currentSources) {
    expect(await readFile(file, "utf8")).not.toMatch(legacyPath);
  }

  const createSource = await readFile(createPage, "utf8");
  expect(createSource).toContain('<Folder name="hello" defaultOpen>');
  expect(createSource).toContain('<File name="service.ts" />');
  expect(createSource).not.toContain('    <Folder name="functions" defaultOpen>');
  expect(createSource).not.toContain('    <Folder name="services"');
});

test("builds and starts from the repository root on Railway", async () => {
  const manifest = (await Bun.file(resolve(import.meta.dir, "../package.json")).json()) as {
    scripts: Record<string, string>;
  };
  const railway = (await Bun.file(resolve(import.meta.dir, "../../../railway.json")).json()) as {
    build: { builder: string; dockerfilePath: string };
    deploy: { startCommand: string; healthcheckPath: string };
  };

  expect(manifest.scripts.start).toBe("next start --hostname 0.0.0.0");
  expect(railway.build).toEqual({
    builder: "DOCKERFILE",
    dockerfilePath: "Dockerfile.docs",
  });
  expect(railway.deploy).toMatchObject({
    startCommand: "bun --cwd=apps/docs run start",
    healthcheckPath: "/docs",
  });
});

test("derives capability and related-guide content from the typed catalogs", async () => {
  const capabilities = renderCapabilities();
  for (const feature of features) {
    expect(capabilities).toContain(feature.title);
    expect(capabilities).toContain(`/docs/${feature.guide}`);
    expect(capabilities).toContain(`/docs/api/${feature.apiPackage}`);
  }

  for (const relation of guideRelations) {
    const generated = await readFile(
      resolve(content, `../generated/related/${relation.path.replaceAll("/", "-")}.mdx`),
      "utf8",
    );
    expect(generated).toBe(renderRelated(relation));
    expect(generated).toContain("Do not edit");
  }

  const create = getCliHelpModel("test").commands.find(({ name }) => name === "create")!;
  const generatedOptions = await readFile(
    resolve(content, "../generated/create-options.mdx"),
    "utf8",
  );
  expect(renderCreateOptions(create)).toContain("Generated by apps/docs/scripts/generate.ts");
  for (const option of create.options) expect(generatedOptions).toContain(`--${option.name}`);

  const coverage = (await Bun.file(resolve(content, "../generated/coverage.json")).json()) as {
    features: { id: string }[];
    guides: { path: string }[];
  };
  expect(coverage.features.map(({ id }) => id)).toEqual(features.map(({ id }) => id));
  expect(coverage.guides.map(({ path }) => path)).toEqual(guideRelations.map(({ path }) => path));
});

test("keeps learning guides focused and actionable", async () => {
  const directories = new Set<string>(guideGroups.map(({ directory }) => directory));
  for (const { directory, pages } of guideGroups.filter(
    ({ directory }) => directory !== "operations",
  )) {
    for (const page of pages) {
      if (directories.has(`${directory}/${page}`)) continue;
      const source = await readFile(resolve(content, directory, `${page}.mdx`), "utf8");
      expect(source).toMatch(/^---\ntitle: .+\ndescription: .+\n---/);
      if (!["events", "storage", "caching", "ai"].includes(directory) || page !== "index") {
        expect(source).toMatch(/```sh|<include[^>]*lang="ts"/);
      }
      const focusedGuide =
        ["events", "storage", "caching", "ai"].includes(directory) ||
        (directory === "async" && ["events", "listeners"].includes(page));
      if (focusedGuide) {
        expect(source).not.toContain("content/generated/related/");
      } else {
        expect(source).toContain(
          `content/generated/related/${directory.replaceAll("/", "-")}-${page}.mdx`,
        );
      }
    }
  }
});

async function markdownFiles(directory: string): Promise<string[]> {
  const found: string[] = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) found.push(...(await markdownFiles(path)));
    else if (/\.mdx?$/.test(entry.name)) found.push(path);
  }
  return found;
}
