import { expect, test } from "bun:test";
import { readFile, readdir } from "node:fs/promises";
import { join, resolve } from "node:path";

const content = resolve(import.meta.dir, "../content/docs");

test("publishes authored, CLI, and application-facing API documentation", async () => {
  const files = await markdownFiles(content);
  expect(files.length).toBeGreaterThanOrEqual(34);
  expect(await readFile(resolve(content, "operations/cli-reference.mdx"), "utf8")).toContain(
    "`zsys graph diff <before> <after>`",
  );
  for (const packageName of [
    "app",
    "schema",
    "functions",
    "routes",
    "events",
    "jobs",
    "buckets",
    "cache",
    "tools",
    "agents",
    "testing",
  ]) {
    const reference = await readFile(resolve(content, `api/${packageName}.mdx`), "utf8");
    expect(reference).toContain("Generated by apps/docs/scripts/generate.ts");
    expect(reference).toContain("**Signature**");
  }
});

test("keeps guides backed by executable examples and self-hosted discovery", async () => {
  const routes = await readFile(resolve(content, "http/routes.mdx"), "utf8");
  const events = await readFile(resolve(content, "async/events.mdx"), "utf8");
  expect(routes).toContain("examples/commerce/src/routes/orders/[orderId]/route.ts");
  expect(events).toContain("examples/commerce/src/events/order-receipt.event.ts");
  expect(await Bun.file(resolve(import.meta.dir, "../app/api/search/route.ts")).text()).toContain(
    "createFromSource(source)",
  );
  expect(await Bun.file(resolve(import.meta.dir, "../app/llms.txt/route.ts")).text()).toContain(
    "llms(source).index()",
  );
});

async function markdownFiles(directory: string): Promise<string[]> {
  const found: string[] = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) found.push(...(await markdownFiles(path)));
    else if (/\.mdx?$/.test(entry.name)) found.push(path);
  }
  return found;
}
