import { expect, test } from "bun:test";
import { readFile, readdir } from "node:fs/promises";
import { join, resolve } from "node:path";
import { features } from "../scripts/feature-catalog.js";
import { apiPackageDefinitions } from "../scripts/documentation-catalog.js";
import { exampleDefinitions, primaryCapabilities } from "../components/landing/data.js";
import {
  renderCapabilities,
  renderCreateOptions,
  renderRelated,
} from "../scripts/generate-guides.js";
import { guideGroups, guideRelations } from "../scripts/guide-catalog.js";
import { getCliHelpModel } from "@relkit/cli/help";

const content = resolve(import.meta.dir, "../content/docs");

test("publishes authored, CLI, and application-facing API documentation", async () => {
  const files = await markdownFiles(content);
  expect(files.length).toBeGreaterThanOrEqual(34);
  expect(await readFile(resolve(content, "operations/cli-reference.mdx"), "utf8")).toContain(
    "`relkit graph diff <before> <after>`",
  );
  for (const { group, packageName, slug } of apiPackageDefinitions) {
    const reference = await readFile(resolve(content, `api/${slug}.mdx`), "utf8");
    expect(reference).toContain("Generated by apps/docs/scripts/generate.ts");
    expect(reference).toContain(packageName);
    if (group === "core") expect(reference).toContain("**Signature**");
  }
});

test("leads with the five product concepts and separates guides from API reference", async () => {
  expect(exampleDefinitions.map(({ title }) => title)).toEqual([
    "Service",
    "Routes",
    "Functions",
    "Events",
    "Observability",
  ]);
  expect(primaryCapabilities.map(({ title }) => title)).toEqual(
    exampleDefinitions.map(({ title }) => title),
  );
  const landingSources = exampleDefinitions.map(({ source }) => source);
  for (const removed of [
    "apps/docs/examples/landing/define-app.ts",
    "apps/docs/examples/landing/local-redis.ts",
    "apps/docs/examples/landing/aws-s3.ts",
  ])
    expect(landingSources).not.toContain(removed);

  expect(await Bun.file(resolve(content, "api/meta.json")).json()).toMatchObject({
    title: "API Reference",
    pages: expect.arrayContaining(["app", "integrations"]),
  });
  expect(await Bun.file(resolve(content, "api/integrations/meta.json")).json()).toMatchObject({
    title: "Integrations",
    pages: expect.arrayContaining(["docker", "redis", "s3", "sentry", "otlp"]),
  });
});

test("keeps Core concepts near Start and retires the duplicate Async section", async () => {
  expect(guideGroups.map(({ directory }) => directory).slice(0, 3)).toEqual([
    "start",
    "fundamentals",
    "service",
  ]);
  expect(guideGroups.find(({ directory }) => directory === "fundamentals")).toMatchObject({
    title: "Core concepts",
    pages: ["index", "application", "functions", "schemas", "errors", "context", "environment"],
  });
  expect(guideGroups.find(({ directory }) => directory === "operations")).toMatchObject({
    title: "Operations",
    pages: [
      "index",
      "observability",
      "inspector",
      "testing",
      "deployment",
      "troubleshooting",
      "cli-reference",
    ],
  });
  expect(guideGroups.some(({ directory }) => directory === "async")).toBe(false);

  const redirects = await readFile(resolve(import.meta.dir, "../next.config.mjs"), "utf8");
  for (const [source, destination] of [
    ["events", "/docs/events"],
    ["listeners", "/docs/events/consume"],
    ["jobs", "/docs/jobs"],
    ["schedules", "/docs/jobs/schedules"],
  ]) {
    expect(redirects).toContain(`["/docs/async/${source}", "${destination}"]`);
  }
});

test("documents current Docker-backed service versions from integration source", async () => {
  const guide = await readFile(resolve(content, "integrations/local-docker.mdx"), "utf8");
  for (const source of [
    "integrations/packages/redis/src/local-recipe/index.ts",
    "integrations/packages/s3/src/local-recipe/index.ts",
  ]) {
    const recipe = await readFile(resolve(import.meta.dir, "../../..", source), "utf8");
    const image = recipe.match(/"([^\"]+@sha256:[a-f0-9]{64})"/)?.[1];
    expect(image).toBeDefined();
    const [tag, digest] = image!.split("@");
    expect(guide).toContain(tag!);
    expect(guide).toContain(digest!);
  }
});

test("keeps guides backed by executable examples and self-hosted discovery", async () => {
  const files = await markdownFiles(content);
  const routes = await readFile(resolve(content, "http/routes.mdx"), "utf8");
  const events = await readFile(resolve(content, "events/define.mdx"), "utf8");
  const listeners = await readFile(resolve(content, "events/consume.mdx"), "utf8");
  expect(routes).toContain("examples/commerce/src/routes/orders/[orderId]/route.ts");
  expect(events).toContain("apps/docs/examples/events/order-created.event.ts");
  expect(listeners).toContain("apps/docs/examples/events/order-confirmation.function.ts");
  expect(await Bun.file(resolve(import.meta.dir, "../app/api/search/route.ts")).text()).toContain(
    "createFromSource(source)",
  );
  expect(await Bun.file(resolve(import.meta.dir, "../app/llms.txt/route.ts")).text()).toContain(
    "llms(source).index()",
  );

  for (const file of files.filter(
    (file) => !file.includes("/api/") && !file.endsWith("/operations/cli-reference.mdx"),
  )) {
    expect(await readFile(file, "utf8")).not.toMatch(/^\s*```(?:ts|tsx)\b/m);
  }

  for (const removedBundle of [
    "start/check-build-deploy.mdx",
    "fundamentals/schemas-errors-context.mdx",
    "http/uploads-middleware-rate-limits.mdx",
    "http/responses-openapi-clients.mdx",
    "resources-ai/buckets-cache.mdx",
    "resources-ai/tools-agents.mdx",
    "async/events.mdx",
    "async/jobs.mdx",
    "async/listeners.mdx",
    "async/schedules.mdx",
    "fundamentals/providers.mdx",
    "fundamentals/services.mdx",
    "fundamentals/domain-first-migration.mdx",
  ]) {
    expect(files).not.toContain(resolve(content, removedBundle));
  }
});

test("keeps current guidance on the domain-first application layout", async () => {
  const createPage = resolve(content, "start/create-an-app.mdx");
  const currentSources = [
    ...(await markdownFiles(content)).filter((file) => !file.includes("/api/")),
    ...(await sourceFiles(resolve(import.meta.dir, "../examples/landing"))),
    resolve(import.meta.dir, "../../../docs/getting-started.md"),
    resolve(import.meta.dir, "../../../docs/testing.md"),
  ];
  const legacyPath =
    /(?:^|[\s"'`(])(?:src\/(?:env\.ts|(?:functions|events|services|agents|jobs|cache|buckets|tools|middleware|transforms|shared)(?:\/|\b))|@app\/(?:functions|events|services|agents|jobs|cache|buckets|tools|middleware|transforms|shared)(?:\/|\b))/m;

  for (const file of currentSources) {
    expect(await readFile(file, "utf8")).not.toMatch(legacyPath);
  }

  const createSource = await readFile(createPage, "utf8");
  expect(createSource).toContain('<Folder name="hello" defaultOpen>');
  expect(createSource).toContain('<File name="service.ts" />');
  expect(createSource).not.toContain('    <Folder name="functions" defaultOpen>');
  expect(createSource).not.toContain('    <Folder name="services"');
});

test("builds and starts from the repository root on Railway", async () => {
  const manifest = (await Bun.file(resolve(import.meta.dir, "../package.json")).json()) as {
    scripts: Record<string, string>;
  };
  const railway = (await Bun.file(resolve(import.meta.dir, "../../../railway.json")).json()) as {
    build: { builder: string; dockerfilePath: string };
    deploy: { startCommand: string; healthcheckPath: string };
  };

  expect(manifest.scripts.start).toBe("next start --hostname 0.0.0.0");
  expect(railway.build).toEqual({
    builder: "DOCKERFILE",
    dockerfilePath: "Dockerfile.docs",
  });
  expect(railway.deploy).toMatchObject({
    startCommand: "bun --cwd=apps/docs run start",
    healthcheckPath: "/docs",
  });
});

test("derives capability and related-guide content from the typed catalogs", async () => {
  const capabilities = renderCapabilities();
  for (const feature of features) {
    expect(capabilities).toContain(feature.title);
    expect(capabilities).toContain(`/docs/${feature.guide}`);
    expect(capabilities).toContain(`/docs/api/${feature.apiPackage}`);
  }

  for (const relation of guideRelations) {
    const generated = await readFile(
      resolve(content, `../generated/related/${relation.path.replaceAll("/", "-")}.mdx`),
      "utf8",
    );
    expect(generated).toBe(renderRelated(relation));
    expect(generated).toContain("Do not edit");
  }

  const create = getCliHelpModel("test").commands.find(({ name }) => name === "create")!;
  const generatedOptions = await readFile(
    resolve(content, "../generated/create-options.mdx"),
    "utf8",
  );
  expect(renderCreateOptions(create)).toContain("Generated by apps/docs/scripts/generate.ts");
  for (const option of create.options) expect(generatedOptions).toContain(`--${option.name}`);

  const coverage = (await Bun.file(resolve(content, "../generated/coverage.json")).json()) as {
    features: { id: string }[];
    guides: { path: string }[];
  };
  expect(coverage.features.map(({ id }) => id)).toEqual(features.map(({ id }) => id));
  expect(coverage.guides.map(({ path }) => path)).toEqual(guideRelations.map(({ path }) => path));
});

test("keeps learning guides focused and actionable", async () => {
  const directories = new Set<string>(guideGroups.map(({ directory }) => directory));
  for (const { directory, pages } of guideGroups.filter(
    ({ directory }) => directory !== "operations",
  )) {
    for (const page of pages) {
      if (directories.has(`${directory}/${page}`)) continue;
      const source = await readFile(resolve(content, directory, `${page}.mdx`), "utf8");
      expect(source).toMatch(/^---\ntitle: .+\ndescription: .+\n---/);
      if (!["events", "storage", "caching", "ai"].includes(directory) || page !== "index") {
        expect(source).toMatch(/```sh|<include[^>]*lang="ts"/);
      }
      const focusedGuide =
        ["events", "storage", "caching", "ai"].includes(directory) ||
        (directory === "async" && ["events", "listeners"].includes(page));
      if (focusedGuide) {
        expect(source).not.toContain("content/generated/related/");
      } else {
        expect(source).toContain(
          `content/generated/related/${directory.replaceAll("/", "-")}-${page}.mdx`,
        );
      }
    }
  }
});

async function markdownFiles(directory: string): Promise<string[]> {
  const found: string[] = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) found.push(...(await markdownFiles(path)));
    else if (/\.mdx?$/.test(entry.name)) found.push(path);
  }
  return found;
}

async function sourceFiles(directory: string): Promise<string[]> {
  return (await readdir(directory, { withFileTypes: true }))
    .filter((entry) => entry.isFile() && entry.name.endsWith(".ts"))
    .map((entry) => join(directory, entry.name));
}
