import type { Effect } from "effect";

/** Fixed operation labels for agent telemetry; no user value is a label.
 * @example const operation: AgentOperation = "runtime.invoke-tool";
 */
export type AgentOperation =
  | "client.controls"
  | "client.chat"
  | "client.copy"
  | "validation.schema"
  | "validation.is-schema"
  | "validation.positive-integer"
  | "validation.is-positive-integer"
  | "validation.is-record"
  | "capture.policy"
  | "capture.content"
  | "capture.span"
  | "client-schema.merge"
  | "client-schema.select"
  | "client-schema.project"
  | "client-events.project"
  | "graph-state.select"
  | "graph-interruption.response"
  | "graph-interruption.requests"
  | "graph-interruption.is-error"
  | "thread-transition.decide"
  | "runtime.invoke"
  | "runtime.create"
  | "approval.requires"
  | "approval.create"
  | "approval.approve"
  | "approval.deny"
  | "approval.assert-granted"
  | "approval.is-record"
  | "model-selector.normalize"
  | "model-selector.parse"
  | "model-selector.resolve"
  | "persistence.release"
  | "persistence.resolve-graph"
  | "persistence.resolve-agent"
  | "bucket.list"
  | "bucket.delete"
  | "bucket.glob"
  | "bucket.grep"
  | "bucket.read-data"
  | "bucket.write-data"
  | "bucket.scoped-keys"
  | "bucket.info"
  | "bucket.read-raw"
  | "bucket.read"
  | "bucket.write"
  | "bucket.edit"
  | "bucket.upload"
  | "bucket.download"
  | "bucket.create"
  | "bucket.thread"
  | "definition.copy-instructions"
  | "definition.is-instructions"
  | "definition.is-descriptor"
  | "definition.assert-descriptor"
  | "definition.normalize-model"
  | "definition.copy-deep"
  | "definition.has-deep"
  | "definition.is-model"
  | "definition.copy-middleware"
  | "definition.state-keys"
  | "definition.copy-tools"
  | "definition.tool-refs"
  | "graph.validate-resume"
  | "graph.waiting"
  | "graph.config"
  | "graph.resume-command"
  | "graph-node.destinations"
  | "graph-node.copy-ends"
  | "graph-node.result"
  | "graph-node.input"
  | "graph-node.handle"
  | "graph-node.define"
  | "graph-node.is-descriptor"
  | "definition.copy-limits"
  | "definition.define"
  | "generated.id"
  | "generated.create"
  | "generated.is-function"
  | "persistence.is-resource"
  | "persistence.assert-protocol"
  | "persistence.define-checkpointer"
  | "persistence.define-memory"
  | "runtime.resolve-model"
  | "runtime.content-limits"
  | "graph.invoke"
  | "graph.workflow"
  | "graph.requires-persistence"
  | "graph.define"
  | "graph.execution"
  | "graph.is-descriptor"
  | "graph.subgraph-create"
  | "graph.subgraph-is-node"
  | "graph.subgraph-source"
  | "native-hitl.response-schema"
  | "native-hitl.is-request"
  | "native-hitl.public-request"
  | "native-hitl.is-decision"
  | "native-hitl.is-record"
  | "native-hitl.resume-command"
  | "native-hitl.waiting"
  | "native-hitl.validate-reply"
  | "graph.compile"
  | "graph.route"
  | "graph.edge-builder"
  | "graph.add-edge"
  | "graph.add-conditional-edge"
  | "graph.destination"
  | "graph.validate-route"
  | "graph.prepare-definition"
  | "runtime.validate-value"
  | "runtime.json-value"
  | "runtime.model-failure"
  | "runtime.selected-state-schemas"
  | "graph-node.validate-destinations"
  | "graph-node.command-update"
  | "graph-node.validated-update"
  | "graph-node.validated-value"
  | "bucket.context"
  | "bucket.virtual-path"
  | "bucket.key"
  | "bucket.file-path"
  | "bucket.page"
  | "bucket.control-failure"
  | "bucket.error-message"
  | "bucket.text-mime-type"
  | "runtime.collect-native-events"
  | "runtime.emit-native-tool-event"
  | "runtime.selected-state"
  | "runtime.select-state-fields"
  | "runtime.native-public-event"
  | "runtime.public-event-value"
  | "runtime.public-tool-value"
  | "runtime.message-update"
  | "runtime.native-limits"
  | "runtime.model-limit"
  | "runtime.tool-limit"
  | "runtime.combine-native-tools"
  | "runtime.native-instructions"
  | "runtime.load-deepagents"
  | "runtime.assert-dependencies"
  | "runtime.model-tool-name"
  | "runtime.find-model-tool"
  | "runtime.find-tool"
  | "runtime.run-tool"
  | "runtime.emit-tool"
  | "runtime.resolve-approval"
  | "runtime.create-tool-dispatcher"
  | "runtime.invoke-tool"
  | "graph.stream-compiled"
  | "graph.run-compiled"
  | "observability.emit-edge"
  | "runtime.create-native-tools"
  | "runtime.create-agent-tools"
  | "runtime.response-format"
  | "runtime.child-model"
  | "runtime.create-subagents"
  | "runtime.create-native-agent"
  | "runtime.native-messages"
  | "runtime.response-value"
  | "runtime.unwrap-native-cause"
  | "runtime.run-loop"
  | "signal.failure"
  | "signal.create"
  | "signal.acquire"
  | "signal.with-signal"
  | "client.agent-metadata"
  | "client.graph-metadata";

/** Replaceable observer used by Effect operations and deterministic tests. */
export interface AgentTelemetryService {
  /** Records an operation without changing its Effect channels.
   * @param operation - Fixed agent operation name.
   * @param effect - Work to instrument.
   * @returns The same success, error, and dependency channels.
   * @example telemetry.observe("capture.policy", Effect.succeed({ mode: "off" }));
   */
  readonly observe: <A, E, R>(
    operation: AgentOperation,
    effect: Effect.Effect<A, E, R>,
  ) => Effect.Effect<A, E, R>;
}
