import { GRAPH_VERSION } from "@relkit/contracts";
import type { ApplicationGraph } from "../src/index.js";

export const source = { file: "src/app.ts", line: 1, column: 1 } as const;

export function graph(): ApplicationGraph {
  return {
    contractVersion: GRAPH_VERSION,
    appId: "orders",
    nodes: [
      {
        kind: "function",
        invocationMode: "callable",
        id: "orders.create",
        domainId: "orders",
        exposure: "public",
        source,
        input: { type: "object" },
        output: { type: "object" },
      },
      {
        kind: "trigger",
        id: "orders.route",
        source,
        triggerType: "http",
        targetFunctionId: "orders.create",
        config: {
          method: "POST",
          path: "/orders",
          request: { kind: "input" },
          responses: [],
          middleware: [],
          transforms: [],
        },
      },
      {
        kind: "event",
        id: "orders.created",
        source,
        version: 1,
        input: { type: "object" },
        profile: "default",
      },
      {
        kind: "function",
        invocationMode: "event-only",
        id: "orders.react",
        source,
        input: { type: "object" },
        output: { "x-relkit-void": true },
      },
      {
        kind: "trigger",
        id: "orders.listener",
        source,
        triggerType: "event",
        targetFunctionId: "orders.react",
        config: {
          eventId: "orders.created",
          eventVersion: 1,
          delivery: "durable",
        },
      },
      {
        kind: "job",
        id: "orders.refresh",
        source,
        input: { type: "object" },
        targetFunctionId: "orders.create",
        profile: "default",
        schedule: [{ id: "hourly", cron: "0 * * * *" }],
      },
      {
        kind: "bucket",
        id: "orders.files",
        source,
        profile: "default",
        visibility: "private",
      },
      {
        kind: "cache",
        id: "orders.cache",
        source,
        key: { type: "string" },
        value: { type: "string" },
        profile: "default",
      },
      {
        kind: "tool",
        id: "orders.lookup-tool",
        source,
        targetFunctionId: "orders.create",
        description: "lookup",
        sideEffect: "read",
        approval: "never",
        mcp: false,
      },
      {
        kind: "agent",
        id: "orders.agent",
        source,
        input: { type: "object" },
        output: { type: "object" },
        model: "default",
        instructions: "help",
        toolIds: ["orders.lookup-tool"],
        limits: { maxSteps: 2 },
        profile: "default",
        generatedFunction: {
          generated: true,
          generatedBy: "agent",
          agentId: "orders.agent",
          functionId: "relkit.agent.orders.agent.invoke",
        },
      },
      {
        kind: "provider",
        id: "provider.bucket.default",
        source,
        profile: "default",
        capability: "bucket",
        adapter: {
          integrationId: "s3",
          adapterId: "s3",
          protocolVersion: 1,
          behavior: {},
          connectionContract: {},
          connection: {},
          features: [],
        },
        providerSource: { kind: "connected" },
        namedValues: [],
        deploymentRoles: [],
      },
      {
        kind: "service",
        id: "orders",
        source,
        title: "Orders",
        functions: [{ name: "create", functionId: "orders.create" }],
        events: [],
      },
    ],
    edges: [],
  };
}
