import { reservePort, waitFor } from "./native-stack.ts";

export const postgresImage =
  "postgres:16-alpine@sha256:cf78e76683b9ca8c5733cbbdce6c9262b45b6767934dd0a95e671f9a0fc20685";
const password = "relkit-effect-mq-password";

const ddl = `
create table effect_mq_jobs (id text primary key, name text not null, queue text not null, state text not null, priority integer not null default 0, seq bigint generated by default as identity, payload jsonb, metadata jsonb not null default '{}'::jsonb, attempts_max integer not null, attempts_made integer not null default 0, stalled_count integer not null default 0, backoff jsonb, keep jsonb, timeout_ms bigint, cancel_requested boolean not null default false, dedupe_key text, trace jsonb, parent jsonb, flow_fail_fast boolean, flow_pending integer, flow_completed integer, flow_failed integer, flow_cancelled integer, run_at timestamptz not null, enqueued_at timestamptz not null, processed_at timestamptz, finished_at timestamptz, exit jsonb, failed_reason text, lock_token text, lock_expires_at timestamptz);
create table effect_mq_job_attempts (job_id text not null references effect_mq_jobs(id) on delete cascade, attempt integer not null, outcome text not null, started_at timestamptz, finished_at timestamptz not null, exit jsonb, primary key (job_id, attempt));
create table effect_mq_schedules (key text primary key, job_name text not null, queue text not null, cron text, tz text, every_ms bigint, payload jsonb, metadata jsonb not null default '{}'::jsonb, priority integer not null default 0, attempts_max integer not null, backoff jsonb, keep jsonb, timeout_ms bigint, group_name text, next_run_at timestamptz not null);
create table effect_mq_dedupe (name text not null, key text not null, job_id text not null, window_expires_at timestamptz, primary key (name, key));
create table effect_mq_flow_children (flow_id text not null, child_key text not null, name text not null, store_key text not null, spec jsonb not null, status text not null, exit jsonb, failed_reason text, cascaded boolean not null, pending_since timestamptz not null, primary key (flow_id, child_key));
create table effect_mq_flow_outbox (id bigserial primary key, flow_name text not null, parent_store_key text not null, report jsonb not null);
create table effect_mq_queue_control (queue text primary key, paused boolean not null default false);
`;

export async function docker(args: readonly string[], tolerate = false) {
  const child = Bun.spawn(["docker", ...args], { stdout: "pipe", stderr: "pipe" });
  const [exitCode, stdout, stderr] = await Promise.all([
    child.exited,
    new Response(child.stdout).text(),
    new Response(child.stderr).text(),
  ]);
  if (exitCode !== 0 && !tolerate) throw new Error(`docker failed: ${stderr.trim()}`);
  return stdout.trim();
}

export async function startPostgres() {
  const port = await reservePort();
  const suffix = crypto.randomUUID().replaceAll("-", "").slice(0, 10);
  const container = `relkit-effect-mq-${suffix}`;
  const volume = `${container}-data`;
  const url = `postgres://postgres:${password}@127.0.0.1:${port}/postgres`;
  await docker(["pull", postgresImage]);
  await docker(["volume", "create", volume]);
  await docker([
    "run",
    "-d",
    "--name",
    container,
    "-e",
    "POSTGRES_PASSWORD=" + password,
    "-v",
    `${volume}:/var/lib/postgresql/data`,
    "-p",
    `127.0.0.1:${port}:5432`,
    postgresImage,
  ]);
  await waitFor("effect-mq PostgreSQL", async () =>
    (
      await docker(["exec", container, "pg_isready", "-h", "127.0.0.1", "-U", "postgres"], true)
    ).includes("accepting connections"),
  );
  await docker([
    "exec",
    container,
    "psql",
    "-h",
    "127.0.0.1",
    "-U",
    "postgres",
    "-d",
    "postgres",
    "-v",
    "ON_ERROR_STOP=1",
    "-c",
    ddl,
  ]);
  return { container, volume, url };
}
