import { feature, type Feature } from "./documentation-catalog.js";
import { databaseFeature } from "./database-guide-catalog.js";
import { authFeature } from "./auth-guide-catalog.js";

export const features = [
  feature(
    "application",
    "Application configuration",
    "Define application identity and runtime topology.",
    "fundamentals/application",
    "app",
    [["packages/app/src/define-app.ts", "defineApp"]],
    ["templates/default/v1/api/relkit.config.ts"],
  ),
  feature(
    "environment",
    "Environment contracts",
    "Parse, default, and protect runtime configuration.",
    "fundamentals/environment",
    "config",
    [["packages/config/src/env.ts", "defineEnv"]],
    ["templates/default/v1/api/src/platform/env.ts"],
  ),
  feature(
    "providers",
    "Provider bindings",
    "Choose connected, local, or infrastructure-owned adapters without changing handlers.",
    "integrations/index",
    "app",
    [
      ["integrations/packages/docker/src/index.ts", "docker"],
      ["integrations/packages/aws/src/aws.ts", "aws"],
    ],
    ["examples/commerce/relkit.config.ts"],
  ),
  feature(
    "schemas",
    "Runtime schemas",
    "Validate untrusted values while retaining TypeScript inference.",
    "fundamentals/schemas",
    "schema",
    [
      ["packages/schema/src/builder.ts", "z"],
      ["packages/schema/src/standard-schema.ts", "validate"],
    ],
    ["examples/commerce/src/platform/schemas.ts"],
  ),
  feature(
    "functions",
    "Functions",
    "Write one validated handler for every invocation transport.",
    "fundamentals/functions",
    "functions",
    [["packages/functions/src/define-function.ts", "defineFunction"]],
    ["examples/commerce/src/orders/functions/create-order.function.ts"],
  ),
  feature(
    "errors",
    "Declared errors",
    "Expose stable failures with transport and retry policy.",
    "fundamentals/errors",
    "functions",
    [["packages/functions/src/define-error.ts", "defineError"]],
    ["examples/commerce/src/orders/errors/order-not-found.error.ts"],
  ),
  feature(
    "services",
    "Services",
    "Organize capabilities by domain and expose a focused public service boundary.",
    "service/define",
    "services",
    [["packages/services/src/define-service.ts", "defineService"]],
    ["examples/commerce/src/orders/service.ts"],
  ),
  databaseFeature,
  authFeature,
  feature(
    "http",
    "HTTP routes",
    "Map filesystem routes to validated function calls.",
    "http/define",
    "routes",
    [["packages/routes/src/define-route.ts", "defineRoute"]],
    ["examples/commerce/src/routes/orders/[orderId]/route.ts"],
  ),
  feature(
    "middleware",
    "HTTP middleware",
    "Apply request policy to explicit path scopes.",
    "http/middleware",
    "routes",
    [["packages/routes/src/define-middleware.ts", "defineMiddleware"]],
    ["examples/commerce/src/routes/middleware/order-auth.middleware.ts"],
  ),
  feature(
    "clients",
    "Generated clients",
    "Call checked routes through the generated typed contract.",
    "http/generated-clients",
    "client",
    [["packages/client/src/index.ts", "createClient"]],
    ["examples/commerce/src/platform/generated-client.ts"],
  ),
  feature(
    "events",
    "Events",
    "Publish typed facts and process them with independent listeners.",
    "events/index",
    "events",
    [
      ["packages/events/src/define-event.ts", "defineEvent"],
      ["packages/events/src/define-event-function.ts", "defineEventFunction"],
    ],
    ["apps/docs/examples/events/order-created.event.ts"],
  ),
  feature(
    "jobs",
    "Jobs",
    "Queue validated work with bounded retry and concurrency.",
    "jobs/define",
    "jobs",
    [["packages/jobs/src/define-job.ts", "defineJob"]],
    ["apps/docs/examples/jobs/send-receipt.job.ts"],
  ),
  feature(
    "schedules",
    "Schedules",
    "Trigger a job from explicit cron and timezone rules.",
    "jobs/schedules",
    "jobs",
    [["packages/jobs/src/define-job.ts", "defineJob"]],
    ["apps/docs/examples/jobs/send-receipt.job.ts"],
  ),
  feature(
    "buckets",
    "Object buckets",
    "Store, read, and share files from your app.",
    "storage/define",
    "buckets",
    [["packages/buckets/src/define-bucket.ts", "defineBucket"]],
    ["examples/commerce/src/assets/buckets/assets.bucket.ts"],
  ),
  feature(
    "cache",
    "Cache",
    "Reuse expensive lookups and keep cached values fresh.",
    "caching/define",
    "cache",
    [["packages/cache/src/define-cache.ts", "defineCache"]],
    ["examples/commerce/src/orders/cache/prices.cache.ts"],
  ),
  feature(
    "tools",
    "AI tools",
    "Let AI agents and MCP clients use your application's functions.",
    "ai/tools",
    "tools",
    [["packages/tools/src/define-tool.ts", "defineTool"]],
    ["examples/commerce/src/orders/tools/lookup-order.tool.ts"],
  ),
  feature(
    "approvals",
    "Tool approvals",
    "Require an explicit decision before sensitive model actions.",
    "ai/approvals",
    "agents",
    [
      ["packages/agents/src/approval.ts", "approveApproval"],
      ["packages/agents/src/approval.ts", "denyApproval"],
    ],
    ["examples/commerce/src/orders/tools/cancel-order.tool.ts"],
  ),
  feature(
    "agents",
    "Agents",
    "Run bounded model workflows with allowlisted tools and offline tests.",
    "ai/agents",
    "agents",
    [["packages/agents/src/define-agent.ts", "defineAgent"]],
    ["examples/commerce/src/orders/agents/order-support.agent.ts"],
  ),
  feature(
    "testing",
    "Testing",
    "Exercise the engine with HTTP helpers and deterministic fakes.",
    "operations/testing",
    "testing",
    [
      ["packages/testing/src/invoke-function.ts", "invokeFunction"],
      ["packages/testing/src/application.ts", "createTestApplication"],
    ],
    ["templates/default/v1/api/tests/integration/orders.route.test.ts"],
  ),
] as const satisfies readonly Feature[];
