import { feature, type Feature } from "./documentation-catalog.js";

export const features = [
  feature(
    "application",
    "Application configuration",
    "Define application identity and runtime topology.",
    "fundamentals/application",
    "app",
    [["packages/app/src/config.ts", "defineConfig"]],
    ["templates/default/v1/api/relkit.config.ts"],
  ),
  feature(
    "environment",
    "Environment contracts",
    "Parse, default, and protect runtime configuration.",
    "fundamentals/environment",
    "config",
    [["packages/config/src/env.ts", "defineEnv"]],
    ["templates/default/v1/api/src/env.ts"],
  ),
  feature(
    "providers",
    "Provider bindings",
    "Choose local, external, or managed infrastructure without changing handlers.",
    "fundamentals/providers",
    "app",
    [
      ["packages/app/src/providers.ts", "managed"],
      ["packages/app/src/providers.ts", "external"],
    ],
    ["examples/commerce/relkit.config.ts"],
  ),
  feature(
    "schemas",
    "Runtime schemas",
    "Validate untrusted values while retaining TypeScript inference.",
    "fundamentals/schemas",
    "schema",
    [
      ["packages/schema/src/builder.ts", "z"],
      ["packages/schema/src/standard-schema.ts", "validate"],
    ],
    ["examples/commerce/src/shared/schemas.ts"],
  ),
  feature(
    "functions",
    "Functions",
    "Write one validated handler for every invocation transport.",
    "fundamentals/functions",
    "functions",
    [["packages/functions/src/define-function.ts", "defineFunction"]],
    ["examples/commerce/src/functions/orders/create-order.function.ts"],
  ),
  feature(
    "errors",
    "Declared errors",
    "Expose stable failures with transport and retry policy.",
    "fundamentals/errors",
    "functions",
    [["packages/functions/src/define-error.ts", "defineError"]],
    ["examples/commerce/src/errors/order-not-found.error.ts"],
  ),
  feature(
    "services",
    "Services",
    "Group related functions and apply shared invocation policy.",
    "fundamentals/services",
    "services",
    [
      ["packages/services/src/define-service.ts", "defineService"],
      ["packages/services/src/service-middleware.ts", "defineServiceMiddleware"],
    ],
    ["examples/commerce/src/services/orders.service.ts"],
  ),
  feature(
    "http",
    "HTTP routes",
    "Map filesystem routes to validated function calls.",
    "http/routes",
    "routes",
    [["packages/routes/src/define-route.ts", "defineRoute"]],
    ["examples/commerce/src/routes/orders/[orderId]/route.ts"],
  ),
  feature(
    "middleware",
    "HTTP middleware",
    "Apply request policy to explicit path scopes.",
    "http/middleware",
    "routes",
    [["packages/routes/src/define-middleware.ts", "defineMiddleware"]],
    ["examples/commerce/src/middleware/order-auth.middleware.ts"],
  ),
  feature(
    "clients",
    "Generated clients",
    "Call checked routes through the generated typed contract.",
    "http/generated-clients",
    "client",
    [["packages/client/src/index.ts", "createClient"]],
    ["examples/commerce/src/generated-client.ts"],
  ),
  feature(
    "events",
    "Events",
    "Publish typed facts and process them with independent listeners.",
    "async/events",
    "events",
    [
      ["packages/events/src/define-event.ts", "defineEvent"],
      ["packages/events/src/on-event.ts", "onEvent"],
    ],
    ["examples/commerce/src/events/order-created.event.ts"],
  ),
  feature(
    "jobs",
    "Jobs",
    "Queue validated work with bounded retry and concurrency.",
    "async/jobs",
    "jobs",
    [["packages/jobs/src/define-job.ts", "defineJob"]],
    ["examples/commerce/src/jobs/send-receipt.job.ts"],
  ),
  feature(
    "schedules",
    "Schedules",
    "Trigger a job from explicit cron and timezone rules.",
    "async/schedules",
    "jobs",
    [["packages/jobs/src/define-job.ts", "defineJob"]],
    ["examples/commerce/src/jobs/send-receipt.job.ts"],
  ),
  feature(
    "buckets",
    "Object buckets",
    "Store bounded objects through provider-neutral clients.",
    "resources-ai/buckets",
    "buckets",
    [["packages/buckets/src/define-bucket.ts", "defineBucket"]],
    ["examples/commerce/src/buckets/assets.bucket.ts"],
  ),
  feature(
    "cache",
    "Cache",
    "Use schema-backed values, counters, TTLs, and rate-limit state.",
    "resources-ai/cache",
    "cache",
    [["packages/cache/src/define-cache.ts", "defineCache"]],
    ["examples/commerce/src/cache/prices.cache.ts"],
  ),
  feature(
    "tools",
    "AI tools",
    "Expose existing functions to models through bounded metadata.",
    "resources-ai/tools",
    "tools",
    [["packages/tools/src/define-tool.ts", "defineTool"]],
    ["examples/commerce/src/tools/lookup-order.tool.ts"],
  ),
  feature(
    "approvals",
    "Tool approvals",
    "Require an explicit decision before sensitive model actions.",
    "resources-ai/approvals",
    "agents",
    [
      ["packages/agents/src/approval.ts", "approveApproval"],
      ["packages/agents/src/approval.ts", "denyApproval"],
    ],
    ["examples/commerce/src/tools/cancel-order.tool.ts"],
  ),
  feature(
    "agents",
    "Agents",
    "Run bounded model workflows with allowlisted tools and offline tests.",
    "resources-ai/agents",
    "agents",
    [["packages/agents/src/define-agent.ts", "defineAgent"]],
    ["examples/commerce/src/agents/order-support.agent.ts"],
  ),
  feature(
    "testing",
    "Testing",
    "Exercise the engine with HTTP helpers and deterministic fakes.",
    "operations/testing",
    "testing",
    [
      ["packages/testing/src/invoke-function.ts", "invokeFunction"],
      ["packages/testing/src/application.ts", "createTestApplication"],
    ],
    ["templates/default/v1/api/tests/integration/orders.route.test.ts"],
  ),
] as const satisfies readonly Feature[];
