import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { basename, join, relative, resolve } from "node:path";
import { format } from "prettier";
import { getCliHelpModel, type CliHelpCommand } from "@relkit/cli/help";
import { apiPackageDefinitions } from "./documentation-catalog.js";
import { markdownFiles, renderApi } from "./generate-api.js";
import { generateGuides } from "./generate-guides.js";
import { guideGroups, guideRelations } from "./guide-catalog.js";

const root = resolve(import.meta.dir, "../../..");
const content = resolve(import.meta.dir, "../content/docs");
const checkOnly = process.argv.includes("--check");
const apiConcurrency = Number(process.env.RELKIT_DOCGEN_CONCURRENCY ?? "6");
if (!Number.isInteger(apiConcurrency) || apiConcurrency < 1 || apiConcurrency > 6)
  throw new Error("RELKIT_DOCGEN_CONCURRENCY must be an integer from 1 to 6.");
async function main(): Promise<void> {
  const cliPackage = JSON.parse(
    await readFile(resolve(root, "packages/cli/package.json"), "utf8"),
  ) as { readonly version: string };
  const cliModel = getCliHelpModel(cliPackage.version);
  await pruneEmptyNavigation();
  await pruneGeneratedRelations();
  await pruneRemovedApiPages();
  await generateGuides(root, content, cliModel, emit);
  await emit("operations/cli-reference.mdx", renderCliReference(cliModel));
  for (let start = 0; start < apiPackageDefinitions.length; start += apiConcurrency) {
    const results = await Promise.allSettled(
      apiPackageDefinitions
        .slice(start, start + apiConcurrency)
        .map(async (definition) => emit(`api/${definition.slug}.mdx`, await renderApi(definition))),
    );
    for (const result of results) if (result.status === "rejected") throw result.reason;
  }
  console.log(
    checkOnly ? "Generated documentation is current." : "Generated documentation updated.",
  );
}

async function pruneRemovedApiPages(): Promise<void> {
  const apiRoot = resolve(content, "api");
  const expected = new Set(apiPackageDefinitions.map(({ slug }) => `${slug}.mdx`));
  for (const file of await markdownFiles(apiRoot)) {
    if (expected.has(relative(apiRoot, file))) continue;
    const source = await readFile(file, "utf8");
    if (source.includes("Generated by apps/docs/scripts/generate.ts")) await rm(file);
  }
}

function renderCliReference(model: ReturnType<typeof getCliHelpModel>): string {
  return `---\ntitle: CLI reference\ndescription: Generated command, argument, flag, and example reference for relkit ${model.version}.\n---\n\n{/* Generated by apps/docs/scripts/generate.ts. Do not edit. */}\n\nThe command model below is shared with the Effect CLI runtime, so nested help and this page cannot drift.\n\n${renderCommand(model, 2)}\n`;
}

function renderCommand(command: CliHelpCommand, depth: number): string {
  const heading = "#".repeat(Math.min(depth, 6));
  const sections = [
    `${heading} \`${command.usage}\`\n\n${command.description}`,
    command.arguments.length
      ? table(
          "Argument",
          command.arguments.map((item) => [
            item.name,
            item.required ? "required" : "optional",
            item.description,
          ]),
        )
      : "",
    command.options.length
      ? table(
          "Option",
          command.options.map((item) => [
            `--${item.name}${item.aliases?.length ? ` / ${item.aliases.map((alias) => `--${alias}`).join(" / ")}` : ""}`,
            item.values?.join(", ") ?? item.type,
            item.description,
          ]),
        )
      : "",
    command.examples.length
      ? `${heading}# Examples\n\n${command.examples.map((example) => `\`${example.command}\` — ${example.description}`).join("\n\n")}`
      : "",
    ...command.commands.map((child) => renderCommand(child, depth + 1)),
  ];
  return sections.filter(Boolean).join("\n\n");
}

function table(first: string, rows: readonly (readonly string[])[]): string {
  return `| ${first} | Value | Description |\n| --- | --- | --- |\n${rows.map((row) => `| ${row.map(escapeCell).join(" | ")} |`).join("\n")}`;
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

async function emit(path: string, value: string): Promise<void> {
  const destination = resolve(content, path);
  const options = {
    parser: path.endsWith(".json") ? "json" : "mdx",
    printWidth: 100,
    semi: true,
    singleQuote: false,
    trailingComma: "all",
  } as const;
  const formatted = await format(await format(value, options), options);
  if (checkOnly) {
    const current = await readFile(destination, "utf8").catch(() => undefined);
    if (current !== formatted)
      throw new Error(`Generated documentation is stale: ${relative(root, destination)}`);
    return;
  }
  await mkdir(resolve(destination, ".."), { recursive: true });
  await writeFile(destination, formatted);
  if (!basename(destination).includes("meta"))
    console.log(`generated ${relative(root, destination)}`);
}

async function pruneGeneratedRelations(): Promise<void> {
  const directory = resolve(content, "../generated/related");
  const expected = new Set(guideRelations.map(({ path }) => `${path.replaceAll("/", "-")}.mdx`));
  for (const file of await readdir(directory).catch(() => [])) {
    if (expected.has(file)) continue;
    if (checkOnly)
      throw new Error(`Generated documentation is stale: content/generated/related/${file}`);
    await rm(resolve(directory, file));
  }
}

async function pruneEmptyNavigation(): Promise<void> {
  const active = new Set<string>(["api", ...guideGroups.map(({ directory }) => directory)]);
  for (const entry of await readdir(content, { withFileTypes: true })) {
    if (!entry.isDirectory() || active.has(entry.name)) continue;
    const directory = resolve(content, entry.name);
    const files = await readdir(directory);
    if (files.length !== 1 || files[0] !== "meta.json") continue;
    if (checkOnly) throw new Error(`Generated navigation is stale: ${entry.name}/meta.json`);
    await rm(resolve(directory, "meta.json"));
  }
}

await main();
