import { mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { basename, delimiter, join, resolve } from "node:path";
import { apiPackageDefinitions } from "./documentation-catalog.js";

const root = resolve(import.meta.dir, "../../..");
const examplesTsconfig = resolve(root, "apps/docs/docgen.examples.json");

export async function renderApi(
  definition: (typeof apiPackageDefinitions)[number],
): Promise<string> {
  const { directory, packageName, slug, title } = definition;
  await mkdir(resolve(root, ".relkit"), { recursive: true });
  const workingDirectory = await mkdtemp(resolve(root, ".relkit/docgen-cwd-"));
  const temporary = resolve(root, ".relkit", `docgen-output-${basename(workingDirectory)}`);
  try {
    const config = JSON.parse(await readFile(resolve(root, "docgen.json"), "utf8")) as Record<
      string,
      unknown
    >;
    await Promise.all([
      writeFile(
        resolve(workingDirectory, "package.json"),
        await readFile(resolve(root, "package.json")),
      ),
      writeFile(
        resolve(workingDirectory, "docgen.json"),
        JSON.stringify({
          ...config,
          outDir: `../${basename(temporary)}`,
          tscExecutable: resolve(root, "node_modules/.bin/tsc"),
        }),
      ),
    ]);
    const command = [
      resolve(root, "apps/docs/node_modules/.bin/docgen"),
      "--src",
      resolve(root, directory, "src"),
      "--homepage",
      "https://github.com/rel-kit/relkit",
      "--srcLink",
      `https://github.com/rel-kit/relkit/blob/main/${directory}/src/`,
      "--no-enforce-version",
      "--run-examples",
      "--examples-tsconfig-file",
      examplesTsconfig,
      "--parse-tsconfig-file",
      resolve(root, directory, "tsconfig.json"),
    ];
    const child = Bun.spawn(command, {
      cwd: workingDirectory,
      env: {
        ...process.env,
        PATH: `${resolve(root, "apps/docs/node_modules/.bin")}${delimiter}${process.env.PATH ?? ""}`,
      },
      stdout: "pipe",
      stderr: "pipe",
    });
    const [stdout, stderr, exitCode] = await Promise.all([
      new Response(child.stdout).text(),
      new Response(child.stderr).text(),
      child.exited,
    ]);
    if (exitCode !== 0) throw new Error(`docgen failed for ${slug}:\n${stdout}${stderr}`);
    const files = (await markdownFiles(temporary)).filter((file) => file.includes("/modules/"));
    const modules = await Promise.all(
      files.map(async (file) => cleanDocgen(await readFile(file, "utf8"))),
    );
    return `---\ntitle: ${title} API\ndescription: Generated public TypeScript reference for ${packageName}.\n---\n\n{/* Generated by apps/docs/scripts/generate.ts. Do not edit. */}\n\n${modules.join("\n\n")}\n`;
  } finally {
    await Promise.all([
      rm(temporary, { recursive: true, force: true }),
      rm(workingDirectory, { recursive: true, force: true }),
    ]);
  }
}

export async function markdownFiles(directory: string): Promise<string[]> {
  const files: string[] = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) files.push(...(await markdownFiles(path)));
    else if (entry.name.endsWith(".md")) files.push(path);
  }
  return files.sort((left, right) => left.localeCompare(right));
}

function cleanDocgen(markdown: string): string {
  const withoutFrontmatter = markdown.replace(/^---\n[\s\S]*?\n---\n+/, "").trim();
  return withoutFrontmatter.replace(/^## (.+\.ts) overview/m, "## `$1`");
}
