import { access, readFile } from "node:fs/promises";
import { resolve } from "node:path";
import type { CliHelpCommand } from "@relkit/cli/help";
import { apiPackageDefinitions, apiPackageName } from "./documentation-catalog.js";
import { features } from "./feature-catalog.js";
import { guideGroups, guideRelations, startJourney } from "./guide-catalog.js";

type Emit = (path: string, value: string) => Promise<void>;

export async function generateGuides(
  root: string,
  content: string,
  cli: CliHelpCommand,
  emit: Emit,
): Promise<void> {
  await validateCatalog(root, content);
  await emitNavigation(emit);
  await emit("../generated/capabilities.mdx", renderCapabilities());
  await emit(
    "../generated/create-options.mdx",
    renderCommandOptions(command(cli, "create"), cli.options),
  );
  for (const entry of command(cli, "add").commands)
    await emit(
      `../generated/add-${entry.name}-options.mdx`,
      renderCommandOptions(entry, cli.options),
    );
  await emit(
    "../generated/coverage.json",
    `${JSON.stringify({
      generated: "apps/docs/scripts/generate.ts; do not edit",
      features,
      guides: guideRelations,
    })}\n`,
  );
  for (const relation of guideRelations) {
    await emit(
      `../generated/related/${relation.path.replaceAll("/", "-")}.mdx`,
      renderRelated(relation),
    );
  }
}

async function validateCatalog(root: string, content: string): Promise<void> {
  const directories = new Set<string>(guideGroups.map(({ directory }) => directory));
  const authoredPages = new Set([
    "index",
    ...guideGroups.flatMap(({ directory, pages }) =>
      pages
        .filter((page) => page !== "cli-reference" && !directories.has(`${directory}/${page}`))
        .map((page) => `${directory}/${page}`),
    ),
  ]);
  const relatedPages = new Set(guideRelations.map(({ path }) => path));
  const missingRelations = [...authoredPages].filter((page) => !relatedPages.has(page));
  if (missingRelations.length > 0)
    throw new Error(`Guides missing generated relations: ${missingRelations.join(", ")}`);

  for (const relation of guideRelations) {
    await access(resolve(content, `${relation.path}.mdx`));
    if (relation.next !== undefined) await access(resolve(content, `${relation.next}.mdx`));
    for (const example of relation.examples) await access(resolve(root, example));
  }
  for (const feature of features) {
    await access(resolve(content, `${feature.guide}.mdx`));
    for (const example of feature.examples) await access(resolve(root, example));
    for (const { source, name } of feature.entrypoints) {
      const code = await readFile(resolve(root, source), "utf8");
      if (
        !new RegExp(`export\\s+(?:async\\s+)?(?:function|const|class)\\s+${escape(name)}\\b`).test(
          code,
        )
      )
        throw new Error(`${source} does not export documented entrypoint ${name}`);
    }
  }
}

async function emitNavigation(emit: Emit): Promise<void> {
  await emit(
    "meta.json",
    `${JSON.stringify({ title: "RELKIT", pages: ["index", ...guideGroups.map(({ directory }) => directory).filter((directory) => !directory.includes("/")), "api"] }, null, 2)}\n`,
  );
  for (const { directory, title, icon, pages } of guideGroups)
    await emit(`${directory}/meta.json`, `${JSON.stringify({ title, icon, pages }, null, 2)}\n`);
  await emit(
    "api/meta.json",
    `${JSON.stringify(
      {
        title: "API Reference",
        icon: "Braces",
        pages: [
          ...apiPackageDefinitions.filter(({ group }) => group === "core").map(({ slug }) => slug),
          "integrations",
        ],
      },
      null,
      2,
    )}\n`,
  );
  await emit(
    "api/integrations/meta.json",
    `${JSON.stringify(
      {
        title: "Integrations",
        icon: "Plug",
        pages: apiPackageDefinitions
          .filter(({ group }) => group === "integrations")
          .map(({ slug }) => slug.replace("integrations/", "")),
      },
      null,
      2,
    )}\n`,
  );
}

export function renderCapabilities(): string {
  const cards = features
    .map(
      ({ title, summary, guide }) =>
        `<Card title="${title}" description="${summary}" href="/docs/${guide}" />`,
    )
    .join("\n");
  const rows = features
    .map(({ title, summary, apiPackage }) => `| [${title}](/docs/api/${apiPackage}) | ${summary} |`)
    .join("\n");
  return `{/* Generated by apps/docs/scripts/generate.ts. Do not edit. */}

<Cards>
${cards}
</Cards>

| Capability | What it gives you |
| --- | --- |
${rows}
`;
}

export function renderRelated(relation: (typeof guideRelations)[number]): string {
  const next = relation.next;
  const href = next?.endsWith("/index") ? next.slice(0, -6) : next;
  const api = relation.api
    .map((name) => `- [\`${apiPackageName(name)}\` API](/docs/api/${name})`)
    .join("\n");
  const examples = relation.examples
    .map((path) => `- [\`${path}\`](https://github.com/rel-kit/relkit/blob/main/${path})`)
    .join("\n");
  return `{/* Generated by apps/docs/scripts/generate.ts. Do not edit. */}
${next === undefined || startJourney.includes(relation.path as (typeof startJourney)[number]) ? "" : `\n## Next step\n\n[${title(next)}](/docs/${href})\n`}
<details>
<summary>Reference and source</summary>

${api}

${examples}

</details>
`;
}

export function renderCommandOptions(
  command: CliHelpCommand,
  inherited: CliHelpCommand["options"] = [],
): string {
  const options = [...inherited, ...command.options]
    .map((option) => {
      const type = option.values?.map((value) => JSON.stringify(value)).join(" | ") ?? option.type;
      return `${JSON.stringify(`--${option.name}`)}: { type: ${JSON.stringify(type)}, description: ${JSON.stringify(option.description)} }`;
    })
    .join(",\n");
  return `{/* Generated by apps/docs/scripts/generate.ts. Do not edit. */}

<TypeTable type={{
${options}
}} />
`;
}

function command(root: CliHelpCommand, name: string): CliHelpCommand {
  const found = root.commands.find((entry) => entry.name === name);
  if (found === undefined) throw new Error(`CLI help model is missing ${name}`);
  return found;
}

function title(path: string): string {
  const chapterTitles: Record<string, string> = {
    "start/create-an-app": "Create and run an application",
    "start/first-route": "Understand and change an endpoint",
    "start/save-orders": "Save and retrieve orders",
    "start/protect-orders": "Protect your orders",
    "start/test-orders": "Test the Orders API",
    "start/local-development": "Inspect and develop locally",
    "start/build-and-run": "Build and run locally",
  };
  if (chapterTitles[path] !== undefined) return chapterTitles[path];
  const group = guideGroups.find(({ directory }) => path === `${directory}/index`);
  if (group !== undefined) return group.title;
  return path
    .replace(/\/index$/, "")
    .split("/")
    .at(-1)!
    .split("-")
    .map((word) => word[0]!.toUpperCase() + word.slice(1))
    .join(" ");
}

function escape(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
