import { access, readFile } from "node:fs/promises";
import { resolve } from "node:path";
import type { CliHelpCommand } from "@relkit/cli/help";
import { apiPackages } from "./documentation-catalog.js";
import { features } from "./feature-catalog.js";
import { guideGroups, guideRelations } from "./guide-catalog.js";

type Emit = (path: string, value: string) => Promise<void>;

export async function generateGuides(
  root: string,
  content: string,
  cli: CliHelpCommand,
  emit: Emit,
): Promise<void> {
  await validateCatalog(root, content);
  await emitNavigation(emit);
  await emit("../generated/capabilities.mdx", renderCapabilities());
  await emit("../generated/create-options.mdx", renderCreateOptions(command(cli, "create")));
  await emit(
    "../generated/coverage.json",
    `${JSON.stringify({
      generated: "apps/docs/scripts/generate.ts; do not edit",
      features,
      guides: guideRelations,
    })}\n`,
  );
  for (const relation of guideRelations) {
    await emit(
      `../generated/related/${relation.path.replaceAll("/", "-")}.mdx`,
      renderRelated(relation),
    );
  }
}

async function validateCatalog(root: string, content: string): Promise<void> {
  const authoredPages = new Set([
    "index",
    ...guideGroups.flatMap(({ directory, pages }) =>
      pages.filter((page) => page !== "cli-reference").map((page) => `${directory}/${page}`),
    ),
  ]);
  const relatedPages = new Set(guideRelations.map(({ path }) => path));
  const missingRelations = [...authoredPages].filter((page) => !relatedPages.has(page));
  if (missingRelations.length > 0)
    throw new Error(`Guides missing generated relations: ${missingRelations.join(", ")}`);

  for (const relation of guideRelations) {
    await access(resolve(content, `${relation.path}.mdx`));
    await access(resolve(content, `${relation.next}.mdx`));
    for (const example of relation.examples) await access(resolve(root, example));
  }
  for (const feature of features) {
    await access(resolve(content, `${feature.guide}.mdx`));
    for (const example of feature.examples) await access(resolve(root, example));
    for (const { source, name } of feature.entrypoints) {
      const code = await readFile(resolve(root, source), "utf8");
      if (
        !new RegExp(`export\\s+(?:async\\s+)?(?:function|const|class)\\s+${escape(name)}\\b`).test(
          code,
        )
      )
        throw new Error(`${source} does not export documented entrypoint ${name}`);
    }
  }
}

async function emitNavigation(emit: Emit): Promise<void> {
  await emit(
    "meta.json",
    `${JSON.stringify({ title: "RELKIT", pages: ["index", ...guideGroups.map(({ directory }) => directory), "api"] }, null, 2)}\n`,
  );
  for (const { directory, title, pages } of guideGroups)
    await emit(`${directory}/meta.json`, `${JSON.stringify({ title, pages }, null, 2)}\n`);
  await emit(
    "api/meta.json",
    `${JSON.stringify({ title: "Generated API reference", pages: apiPackages }, null, 2)}\n`,
  );
}

export function renderCapabilities(): string {
  const cards = features
    .map(
      ({ title, summary, guide }) =>
        `<Card title="${title}" description="${summary}" href="/docs/${guide}" />`,
    )
    .join("\n");
  const rows = features
    .map(({ title, summary, apiPackage }) => `| [${title}](/docs/api/${apiPackage}) | ${summary} |`)
    .join("\n");
  return `{/* Generated by apps/docs/scripts/generate.ts. Do not edit. */}

<Cards>
${cards}
</Cards>

| Capability | What it gives you |
| --- | --- |
${rows}
`;
}

export function renderRelated(relation: (typeof guideRelations)[number]): string {
  const api = relation.api
    .map((name) => `- [\`@relkit/${name}\` API](/docs/api/${name})`)
    .join("\n");
  const examples = relation.examples
    .map((path) => `- [\`${path}\`](https://github.com/rel-kit/relkit/blob/main/${path})`)
    .join("\n");
  return `{/* Generated by apps/docs/scripts/generate.ts. Do not edit. */}

## Continue learning

**Next:** [${title(relation.next)}](/docs/${relation.next})

### Related API

${api}

### Executable examples

${examples}
`;
}

export function renderCreateOptions(create: CliHelpCommand): string {
  const options = create.options
    .map((option) => {
      const type = option.values?.map((value) => JSON.stringify(value)).join(" | ") ?? option.type;
      return `${JSON.stringify(`--${option.name}`)}: { type: ${JSON.stringify(type)}, description: ${JSON.stringify(option.description)} }`;
    })
    .join(",\n");
  return `{/* Generated by apps/docs/scripts/generate.ts. Do not edit. */}

<TypeTable type={{
${options}
}} />
`;
}

function command(root: CliHelpCommand, name: string): CliHelpCommand {
  const found = root.commands.find((entry) => entry.name === name);
  if (found === undefined) throw new Error(`CLI help model is missing ${name}`);
  return found;
}

function title(path: string): string {
  return path
    .split("/")
    .at(-1)!
    .split("-")
    .map((word) => word[0]!.toUpperCase() + word.slice(1))
    .join(" ");
}

function escape(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
