import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { basename, delimiter, join, relative, resolve } from "node:path";
import { format } from "prettier";
import { getCliHelpModel, type CliHelpCommand } from "@relkit/cli/help";
import { generateGuides } from "./generate-guides.js";
import { guideGroups, guideRelations } from "./guide-catalog.js";

const root = resolve(import.meta.dir, "../../..");
const content = resolve(import.meta.dir, "../content/docs");
const checkOnly = process.argv.includes("--check");
const packages = [
  ["app", "Application"],
  ["config", "Configuration"],
  ["schema", "Schema"],
  ["functions", "Functions"],
  ["services", "Services"],
  ["drizzle", "Drizzle"],
  ["better-auth", "Better Auth"],
  ["routes", "Routes"],
  ["events", "Events"],
  ["jobs", "Jobs"],
  ["buckets", "Buckets"],
  ["cache", "Cache"],
  ["tools", "Tools"],
  ["agents", "Agents"],
  ["client", "Client"],
  ["testing", "Testing"],
] as const;

async function main(): Promise<void> {
  const cliPackage = JSON.parse(
    await readFile(resolve(root, "packages/cli/package.json"), "utf8"),
  ) as { readonly version: string };
  const cliModel = getCliHelpModel(cliPackage.version);
  await pruneEmptyNavigation();
  await pruneGeneratedRelations();
  await generateGuides(root, content, cliModel, emit);
  await emit("operations/cli-reference.mdx", renderCliReference(cliModel));
  for (const [slug, title] of packages) await emit(`api/${slug}.mdx`, await renderApi(slug, title));
  console.log(
    checkOnly ? "Generated documentation is current." : "Generated documentation updated.",
  );
}

async function renderApi(slug: string, title: string): Promise<string> {
  const temporary = resolve(root, ".relkit/docgen");
  await rm(temporary, { recursive: true, force: true });
  try {
    const source = resolve(root, `packages/${slug}/src`);
    const command = [
      resolve(import.meta.dir, "../node_modules/.bin/docgen"),
      "--src",
      source,
      "--homepage",
      "https://github.com/rel-kit/relkit",
      "--srcLink",
      `https://github.com/rel-kit/relkit/blob/main/packages/${slug}/src/`,
      "--no-enforce-version",
      "--run-examples",
      "--examples-tsconfig-file",
      resolve(root, "apps/docs/docgen.examples.json"),
      "--parse-tsconfig-file",
      resolve(root, `packages/${slug}/tsconfig.json`),
    ];
    const child = Bun.spawn(command, {
      cwd: root,
      env: {
        ...process.env,
        PATH: `${resolve(import.meta.dir, "../node_modules/.bin")}${delimiter}${process.env.PATH ?? ""}`,
      },
      stdout: "pipe",
      stderr: "pipe",
    });
    const [stdout, stderr, exitCode] = await Promise.all([
      new Response(child.stdout).text(),
      new Response(child.stderr).text(),
      child.exited,
    ]);
    if (exitCode !== 0) throw new Error(`docgen failed for ${slug}:\n${stdout}${stderr}`);
    const files = (await markdownFiles(temporary)).filter((file) => file.includes("/modules/"));
    const modules = await Promise.all(
      files.map(async (file) => cleanDocgen(await readFile(file, "utf8"))),
    );
    return `---\ntitle: ${title} API\ndescription: Generated public TypeScript reference for @relkit/${slug}.\n---\n\n{/* Generated by apps/docs/scripts/generate.ts. Do not edit. */}\n\n${modules.join("\n\n")}\n`;
  } finally {
    await rm(temporary, { recursive: true, force: true });
  }
}

async function markdownFiles(directory: string): Promise<string[]> {
  const files: string[] = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) files.push(...(await markdownFiles(path)));
    else if (entry.name.endsWith(".md")) files.push(path);
  }
  return files.sort((left, right) => left.localeCompare(right));
}

function cleanDocgen(markdown: string): string {
  const withoutFrontmatter = markdown.replace(/^---\n[\s\S]*?\n---\n+/, "").trim();
  return withoutFrontmatter.replace(/^## (.+\.ts) overview/m, "## `$1`");
}

function renderCliReference(model: ReturnType<typeof getCliHelpModel>): string {
  return `---\ntitle: CLI reference\ndescription: Generated command, argument, flag, and example reference for relkit ${model.version}.\n---\n\n{/* Generated by apps/docs/scripts/generate.ts. Do not edit. */}\n\nThe command model below is shared with the Effect CLI runtime, so nested help and this page cannot drift.\n\n${renderCommand(model, 2)}\n`;
}

function renderCommand(command: CliHelpCommand, depth: number): string {
  const heading = "#".repeat(Math.min(depth, 6));
  const sections = [
    `${heading} \`${command.usage}\`\n\n${command.description}`,
    command.arguments.length
      ? table(
          "Argument",
          command.arguments.map((item) => [
            item.name,
            item.required ? "required" : "optional",
            item.description,
          ]),
        )
      : "",
    command.options.length
      ? table(
          "Option",
          command.options.map((item) => [
            `--${item.name}${item.aliases?.length ? ` / ${item.aliases.map((alias) => `--${alias}`).join(" / ")}` : ""}`,
            item.values?.join(", ") ?? item.type,
            item.description,
          ]),
        )
      : "",
    command.examples.length
      ? `${heading}# Examples\n\n${command.examples.map((example) => `\`${example.command}\` — ${example.description}`).join("\n\n")}`
      : "",
    ...command.commands.map((child) => renderCommand(child, depth + 1)),
  ];
  return sections.filter(Boolean).join("\n\n");
}

function table(first: string, rows: readonly (readonly string[])[]): string {
  return `| ${first} | Value | Description |\n| --- | --- | --- |\n${rows.map((row) => `| ${row.map(escapeCell).join(" | ")} |`).join("\n")}`;
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

async function emit(path: string, value: string): Promise<void> {
  const destination = resolve(content, path);
  const formatted = await format(value, {
    parser: path.endsWith(".json") ? "json" : "mdx",
    printWidth: 100,
    semi: true,
    singleQuote: false,
    trailingComma: "all",
  });
  if (checkOnly) {
    const current = await readFile(destination, "utf8").catch(() => undefined);
    if (current !== formatted)
      throw new Error(`Generated documentation is stale: ${relative(root, destination)}`);
    return;
  }
  await mkdir(resolve(destination, ".."), { recursive: true });
  await writeFile(destination, formatted);
  if (!basename(destination).includes("meta"))
    console.log(`generated ${relative(root, destination)}`);
}

async function pruneGeneratedRelations(): Promise<void> {
  const directory = resolve(content, "../generated/related");
  const expected = new Set(guideRelations.map(({ path }) => `${path.replaceAll("/", "-")}.mdx`));
  for (const file of await readdir(directory).catch(() => [])) {
    if (expected.has(file)) continue;
    if (checkOnly)
      throw new Error(`Generated documentation is stale: content/generated/related/${file}`);
    await rm(resolve(directory, file));
  }
}

async function pruneEmptyNavigation(): Promise<void> {
  const active = new Set<string>(["api", ...guideGroups.map(({ directory }) => directory)]);
  for (const entry of await readdir(content, { withFileTypes: true })) {
    if (!entry.isDirectory() || active.has(entry.name)) continue;
    const directory = resolve(content, entry.name);
    const files = await readdir(directory);
    if (files.length !== 1 || files[0] !== "meta.json") continue;
    if (checkOnly) throw new Error(`Generated navigation is stale: ${entry.name}/meta.json`);
    await rm(resolve(directory, "meta.json"));
  }
}

await main();
