/* generated by @zsys/client-generator; do not edit */
export const contractVersion = 1 as const;
export const generatorVersion = 1 as const;
export interface ClientOptions {
  readonly baseUrl?: string;
  readonly fetch?: typeof globalThis.fetch;
}
export type ClientResult<Status extends number, Data> = {
  readonly status: Status;
  readonly data: Data;
};

export type OrdersGetInput = { "note": string; "orderId": string };
type OrdersGetResponse0 = ClientResult<200, { "orderId": string; "totalCents": number }>;
type OrdersGetResponse1 = ClientResult<404, { "code": "orders.not-found"; "data": { "orderId": string }; "kind": "application"; "message": string; "outcome": "declared-error"; "retry": "never"; "status": 404 }>;
type OrdersGetResponse2 = ClientResult<422, { "error": "validation"; "issues": readonly Record<string, unknown>[] }>;
export type OrdersGetSuccess = OrdersGetResponse0;
export type OrdersGetError = OrdersGetResponse1 | OrdersGetResponse2;
export type OrdersGetResult = OrdersGetSuccess | OrdersGetError;
export type OrdersGetStatus = OrdersGetResult["status"];

export interface ZsysClient {
  readonly ordersGet: (input: OrdersGetInput) => Promise<OrdersGetResult>;
}
export type Client = ZsysClient;

export function createClient(options: ClientOptions = {}): ZsysClient {
  const baseUrl = options.baseUrl ?? "";
  const fetcher = options.fetch ?? globalThis.fetch;
  return {
    async ordersGet(input: OrdersGetInput) {
      let path = "/orders/:orderId";
      path = path.replace(":orderId", encodeURIComponent(String(readPath(input, ["orderId"]))));
      const query = new URLSearchParams();
      appendQuery(query, "note", readPath(input, ["note"]));
      const queryString = query.toString();
      const url = joinUrl(baseUrl, path) + (queryString === "" ? "" : `?${queryString}`);
      const headers: Record<string, string> = {};
      const result = await request(fetcher, url, { method: "GET", headers, ...({}) });
      return result as OrdersGetResult;
    },
  };
}

export default createClient;

function joinUrl(baseUrl: string, path: string): string {
  return baseUrl.replace(/\/+$/, "") + (path.startsWith("/") ? path : `/${path}`);
}
function readPath(value: unknown, path: readonly string[]): unknown {
  let current = value;
  for (const key of path) {
    if (current === null || typeof current !== "object") return undefined;
    current = (current as Record<string, unknown>)[key];
  }
  return current;
}
function setBodyValue(target: Record<string, unknown>, path: readonly string[], value: unknown): void {
  if (value === undefined || path.length === 0) return;
  let current = target;
  for (const key of path.slice(0, -1)) {
    const next = current[key]; current = (next && typeof next === "object" && !Array.isArray(next) ? next : (current[key] = {})) as Record<string, unknown>;
  }
  current[path[path.length - 1]!] = value;
}
function appendQuery(query: URLSearchParams, name: string, value: unknown): void {
  if (value === undefined) return;
  if (Array.isArray(value)) value.forEach((item) => query.append(name, String(item)));
  else query.append(name, String(value));
}
function setHeader(headers: Record<string, string>, name: string, value: unknown): void {
  if (value !== undefined) headers[name] = String(value);
}
function replacePathSegments(path: string, token: string, value: unknown): string {
  if ((value === undefined || (Array.isArray(value) && value.length === 0)) && token.endsWith("?")) return path.replace(`/${token}`, "") || "/";
  if (!Array.isArray(value) || value.length === 0) throw new TypeError(`Catch-all path "${token}" needs at least one segment`);
  return path.replace(token, value.map((segment) => encodeURIComponent(String(segment))).join("/"));
}
function appendCookie(cookies: string[], name: string, value: unknown): void {
  if (value !== undefined) cookies.push(`${name}=${encodeURIComponent(String(value))}`);
}
function appendFormValue(form: FormData, name: string, value: unknown): void {
  if (Array.isArray(value)) { value.forEach((item) => appendFormValue(form, name, item)); return; }
  if (value !== undefined) form.append(name, value instanceof Blob ? value : typeof value === "string" ? value : JSON.stringify(value));
}
async function request(fetcher: typeof globalThis.fetch, url: string, init: RequestInit): Promise<{ readonly status: number; readonly data: unknown }> {
  const response = await fetcher(url, init);
  const text = await response.text();
  let data: unknown;
  if (text !== "") { try { data = JSON.parse(text); } catch { data = text; } }
  return { status: response.status, data };
}
