import { Effect, Schema } from "effect";
import { runCompilerSync } from "./compatibility.js";
import { observeCompiler } from "./observability.js";
import type { RuntimeActivationFingerprintInput } from "./activation-fingerprint.types.js";
export type { RuntimeActivationFingerprintInput } from "./activation-fingerprint.types.js";
import { createHash } from "node:crypto";
import type { RuntimeActivationFingerprint } from "@relkit/contracts";

/** Expected empty activation identity or artifact, preserving the legacy TypeError. */
export class ActivationFingerprintError extends Schema.TaggedError<ActivationFingerprintError>()(
  "ActivationFingerprintError",
  { cause: Schema.Defect() },
) {}

/**
 * Hashes generated runtime contracts into a stable activation identity.
 * @param input - Compiler input and source provenance.
 * @returns A lazy effect hashing generated runtime contracts; empty inputs fail with ActivationFingerprintError and unexpected access failures remain defects.
 * @see {@link normalizeCompilationEffect} for shared lazy composition and the execution boundary.
 */
export const createRuntimeActivationFingerprintEffect = Effect.fn(
  "Compiler.createRuntimeActivationFingerprint",
)(
  function* (input: RuntimeActivationFingerprintInput) {
    yield* requiredEffect(input.graphHash, "graphHash");
    yield* requiredEffect(input.manifestSource, "manifestSource");
    if (input.jobsManifestSource !== undefined)
      yield* requiredEffect(input.jobsManifestSource, "jobsManifestSource");
    yield* requiredEffect(input.runtimeIntegrationsPlanSource, "runtimeIntegrationsPlanSource");
    if (input.localServicesPlanSource !== undefined)
      yield* requiredEffect(input.localServicesPlanSource, "localServicesPlanSource");
    if (input.providerOverridesGeneration !== undefined)
      yield* requiredEffect(input.providerOverridesGeneration, "providerOverridesGeneration");
    return Object.freeze({
      graphHash: input.graphHash,
      manifestHash: hashGeneratedArtifact(input.manifestSource),
      ...(input.jobsManifestSource === undefined
        ? {}
        : { jobsManifestHash: hashGeneratedArtifact(input.jobsManifestSource) }),
      runtimeIntegrationsPlanHash: hashGeneratedArtifact(input.runtimeIntegrationsPlanSource),
      ...(input.localServicesPlanSource === undefined
        ? {}
        : { localServicesPlanHash: hashGeneratedArtifact(input.localServicesPlanSource) }),
      ...(input.providerOverridesGeneration === undefined
        ? {}
        : { providerOverridesGeneration: input.providerOverridesGeneration }),
    });
  },
  (effect, input) =>
    observeCompiler("generation", "createRuntimeActivationFingerprint", effect, () => {
      const sources = [
        input.manifestSource,
        input.jobsManifestSource,
        input.runtimeIntegrationsPlanSource,
        input.localServicesPlanSource,
      ].filter((source): source is string => source !== undefined);
      return {
        artifacts: sources.length,
        bytes: sources.reduce((bytes, source) => bytes + Buffer.byteLength(source, "utf8"), 0),
      };
    }),
);

/**
 * Hashes generated runtime contracts into a stable activation identity.
 * @param input - Compiler input and source provenance.
 * @returns Stable hashes for executable runtime contracts and generated bytes.
 */
export function createRuntimeActivationFingerprint(
  input: RuntimeActivationFingerprintInput,
): RuntimeActivationFingerprint {
  return runCompilerSync(
    createRuntimeActivationFingerprintEffect(input).pipe(Effect.mapError((error) => error.cause)),
  );
}

/**
 * Hashes exact generated UTF-8 source bytes with SHA-256.
 * @param source - Source provenance or exact generated content.
 * @returns A SHA-256 fingerprint of the exact UTF-8 source bytes.
 */
export function hashGeneratedArtifact(source: string): string {
  return `sha256:${createHash("sha256").update(source).digest("hex")}`;
}

/**
 * Rejects missing textual activation fingerprint inputs.
 * @param value - Declared metadata inspected without coercion.
 * @param name - Declared binding or parameter name.
 * @returns A lazy effect rejecting empty text with ActivationFingerprintError.
 */
const requiredEffect = Effect.fnUntraced(function* (value: string, name: string) {
  if (value.trim() === "")
    return yield* new ActivationFingerprintError({
      cause: new TypeError(`${name} must not be empty.`),
    });
});
