/**
 * Restricts compiler operation and workload labels to declaration-owned names.
 * Standalone and composed operations share these metrics; source paths and
 * project identities never become metric attributes.
 */
/** Compiler stage names with bounded metric cardinality. */
export type CompilerStage = "normalization" | "generation" | "discovery" | "configuration";

/** Counts of work inspected or emitted; values never become metric labels. */
export interface CompilerWorkload {
  readonly descriptors?: number;
  readonly diagnostics?: number;
  readonly files?: number;
  readonly nodes?: number;
  readonly edges?: number;
  readonly artifacts?: number;
  readonly bytes?: number;
  readonly changed?: number;
  readonly entries?: number;
  readonly schemas?: number;
  readonly registrations?: number;
}

/** Invocation-local workload projection assembled before recording immutable metric values. */
export type MutableCompilerWorkload = {
  -readonly [K in keyof CompilerWorkload]: CompilerWorkload[K];
};

/** Declaration-owned operation labels; caller IDs and paths cannot enter metric attributes. */
export type CompilerOperation =
  | "extensionArtifact"
  | "sourceReaderExists"
  | "sourceReaderRead"
  | "packageSourceResolve"
  | "packageSourceExists"
  | "packageSourceCanonical"
  | "packageSourceReadManifest"
  | "loadPackage"
  | "runtimePackage"
  | "runtimeRegistrations"
  | "packageName"
  | "catalogTarget"
  | "assertAuthoringImport"
  | "acquireEvaluatorDetectors"
  | "allowlistedEnvironment"
  | "bindRouteFile"
  | "buildGraph"
  | "buildGraphEdges"
  | "buildGraphNodes"
  | "checkConventions"
  | "createEvaluatorRequest"
  | "createRuntimeActivationFingerprint"
  | "createWatchDependencyIndex"
  | "decodeEvaluatorFrame"
  | "decodeEvaluatorRequest"
  | "decodeEvaluatorResponse"
  | "encodeErrorId"
  | "encodeEvaluatorFrame"
  | "encodeExportId"
  | "encodeMemberId"
  | "encodeRouteId"
  | "encodeSourceHierarchy"
  | "encodeSourceId"
  | "evaluateCandidate"
  | "evaluateCandidates"
  | "evaluatorResponse"
  | "eventSourceDiagnostics"
  | "extractDescriptors"
  | "factoryFor"
  | "failedResponse"
  | "failureResponse"
  | "finish"
  | "generateContextRegistry"
  | "generateEventRegistry"
  | "generateLocalServicePlan"
  | "generateManifest"
  | "generateRuntimeIntegrationImports"
  | "generateRuntimeIntegrationPlan"
  | "graphNodeFor"
  | "hashGraph"
  | "idPresence"
  | "importFailure"
  | "inferRouteContract"
  | "installFileDetectors"
  | "installNetworkDetectors"
  | "installOutput"
  | "installTimers"
  | "invalidateWatchDependencies"
  | "isEvaluatorRequest"
  | "isEvaluatorResponse"
  | "isSnapshotErrorDescriptor"
  | "jobCompatible"
  | "jobGraphNode"
  | "loadConfig"
  | "makeOutputs"
  | "mapSourceLocations"
  | "mappingCompatible"
  | "matchesExclude"
  | "membersFor"
  | "middlewareForRoute"
  | "normalizeCompilation"
  | "normalizeEventFunctions"
  | "normalizeProjectRoot"
  | "normalizeSourceIdentities"
  | "optionNames"
  | "optionPaths"
  | "parseRouteFilePath"
  | "passAgents"
  | "passCollisions"
  | "passEventTargets"
  | "passEvents"
  | "passExtract"
  | "passGraph"
  | "passIndex"
  | "passJobs"
  | "passLocal"
  | "passNormalize"
  | "passOutputs"
  | "passProviders"
  | "passReferences"
  | "passRoutes"
  | "passSchemas"
  | "passSources"
  | "passTools"
  | "prefilterSources"
  | "readFacts"
  | "readReExport"
  | "resolveImport"
  | "resolveIntegrationPackageRole"
  | "resolveRuntimeIntegrationPackages"
  | "routePathToFilePath"
  | "runEvaluatorProcess"
  | "scanSource"
  | "schema"
  | "schemaEquivalent"
  | "schemaHasAccessors"
  | "schemaProperties"
  | "sideEffectFailure"
  | "snapshotDescriptor"
  | "snapshotModule"
  | "snapshotSchema"
  | "sourceParts"
  | "typecheckProject"
  | "typecheckInputs"
  | "validateBoundaries"
  | "validateConfig"
  | "validateDependencies"
  | "validateDomainServicesAndRoutes"
  | "validateDomains"
  | "validateEventCompatibility"
  | "validateHttpCompatibility"
  | "validateJob"
  | "validateProviderProfile"
  | "validateProviderReleaseSources"
  | "validateProviderSingletons"
  | "validatePublishes"
  | "validateRateLimit"
  | "validateRateLimitStore"
  | "validateServiceFile"
  | "validateRetry"
  | "validateUniqueBucketProfiles"
  | "writeGeneratedArtifacts"
  | "writeIfChanged";
