import { relative, resolve } from "node:path";
import { routePathParameters } from "./route-path-parameters.js";
import { isRouteModule } from "./route-source-checks.js";

export const ROUTE_MODULE_CHECKS_FILE = "route-module-checks.ts";

/** Generates checked TypeScript source, rather than declarations skipped by skipLibCheck. */
export function generateRouteModuleChecks(
  files: readonly string[],
  projectRoot: string,
  generatedDirectory = ".relkit/generated",
): string {
  const output = resolve(projectRoot, generatedDirectory);
  const routes = [...new Set(files.map((file) => file.replaceAll("\\", "/")))]
    .filter((file) => file.startsWith("src/routes/") && isRouteModule(file))
    .sort();
  return [
    "// Generated by RELKIT. Run relkit check after adding or removing route files.",
    'import type { RouteModuleContract } from "@relkit/app/routes";',
    "type AssertModule<Expected, Actual extends Expected> = Actual;",
    ...routes.flatMap((file, index) => {
      const path = relative(output, resolve(projectRoot, file))
        .replaceAll("\\", "/")
        .replace(/\.ts$/, ".js");
      const module = JSON.stringify(path.startsWith(".") ? path : `./${path}`);
      const parameters = routePathParameters(file)
        .map((name) => JSON.stringify(name))
        .join(" | ");
      const contract = `RouteModuleContract<Route${index}${parameters ? `, ${parameters}` : ""}>`;
      return [
        "",
        `// ${file}`,
        `type Route${index} = typeof import(${module});`,
        `export type CheckRoute${index} = AssertModule<${contract}, Route${index}>;`,
      ];
    }),
    "",
    "export {};",
    "",
  ].join("\n");
}
