import type { Effect } from "effect";

/** Fixed names for invocation operations; values must never contain user data.
 * This union bounds metric labels and operation span names.
 * @example const operation: InvocationOperation = "handler.invoke";
 */
export type InvocationOperation =
  | "retry.normalize"
  | "trace.limits"
  | "trace.bound-text"
  | "trace.safe-attribute"
  | "trace.reserved-key"
  | "deadline.compose"
  | "deadline.with"
  | "deadline.timeout"
  | "suspension.is"
  | "suspension.find"
  | "suspension.mark"
  | "failure.is-function"
  | "failure.is-declared"
  | "failure.is-provider"
  | "failure.is-dependency"
  | "failure.is-cancellation"
  | "failure.is-timeout"
  | "failure.required-text"
  | "progress.create"
  | "progress.emit"
  | "progress.settle"
  | "stream.is-output"
  | "stream.lazy-create"
  | "stream.lazy-next"
  | "stream.lazy-return"
  | "stream.lazy-throw"
  | "stream.managed-create"
  | "stream.managed-open"
  | "stream.managed-next"
  | "stream.managed-return"
  | "stream.managed-idle"
  | "span.root-start"
  | "span.complete"
  | "span.snapshot"
  | "span.context"
  | "trace.propagation"
  | "standalone.deadline"
  | "standalone.record-create"
  | "standalone.record-complete"
  | "standalone.parent"
  | "scope.current"
  | "scope.run"
  | "scope.execution-current"
  | "scope.ancestry-current"
  | "scope.ancestry-run"
  | "scope.execution-run"
  | "scope.detached-run"
  | "dispatcher.current"
  | "dispatcher.dispatch"
  | "abort.bridge-create"
  | "abort.dispose"
  | "abort.promise"
  | "context.create"
  | "context.link-signals"
  | "context.unlink-signals"
  | "context.session"
  | "context.log-noop"
  | "validation.schema"
  | "validation.hook"
  | "validation.declared-error"
  | "validation.source"
  | "validation.mode"
  | "validation.next-id"
  | "validation.run-default"
  | "validation.unknown"
  | "identity.create"
  | "identity.bind"
  | "identity.is-bound"
  | "identity.service-bind"
  | "identity.service-get"
  | "identity.resolve"
  | "identity.get"
  | "identity.is-unbound"
  | "standalone.stream-create"
  | "standalone.finisher-create"
  | "standalone.finish"
  | "standalone.lifecycle"
  | "recursion.create"
  | "recursion.ids"
  | "recursion.has"
  | "recursion.enter"
  | "failure.application"
  | "failure.provider"
  | "failure.cancellation"
  | "failure.timeout"
  | "failure.defect"
  | "failure.normalize"
  | "failure.is-invocation"
  | "failure.public-envelope"
  | "failure.detail-remember"
  | "failure.detail-read"
  | "failure.create"
  | "failure.construct"
  | "failure.dependency"
  | "validation.error-create"
  | "validation.error-factory"
  | "clock.create"
  | "clock.now"
  | "clock.sleep"
  | "logger.create"
  | "logger.write"
  | "logger.records"
  | "context.standalone"
  | "context.managed-maps"
  | "context.managed-map"
  | "context.managed-get"
  | "trace.safe-attributes"
  | "trace.child-span"
  | "trace.event"
  | "trace.set-attributes"
  | "trace.rename"
  | "handler.invoke"
  | "lifecycle.function"
  | "lifecycle.value-hook"
  | "lifecycle.base-context"
  | "lifecycle.validate-output"
  | "span.runtime-create"
  | "span.runtime-start"
  | "span.runtime-root"
  | "span.runtime-notify"
  | "span.runtime-capture"
  | "span.runtime-close"
  | "span.end"
  | "span.attribute"
  | "span.rename"
  | "span.event"
  | "span.capture"
  | "span.links"
  | "standalone.invoke"
  | "standalone.dispatcher-create";

/** Observer substituted by deterministic Layers in Effect tests.
 * It must preserve the original Effect success, error, and environment channels.
 * @example const layer = Layer.succeed(InvocationTelemetry, { observe: (_name, effect) => effect });
 */
export interface InvocationTelemetryService {
  /** Records one invocation operation.
   * @param operation - A fixed operation name.
   * @param effect - The operation to observe.
   * @returns The original Effect success and error channels.
   * @example telemetry.observe("retry.normalize", Effect.succeed({ retry: "never" }));
   */
  readonly observe: <A, E, R>(
    operation: InvocationOperation,
    effect: Effect.Effect<A, E, R>,
  ) => Effect.Effect<A, E, R>;
}
