import type { Effect } from "effect";

/** Stable, bounded operation labels recorded in spans and metrics.
 * @example const operation: JobsOperation = "submission.write";
 */
export type JobsOperation =
  | "duration.isInput"
  | "duration.toMillis"
  | "jobName.is"
  | "jobName.assert"
  | "jobName.validate"
  | "identity.stableTuple"
  | "identity.taskOperation"
  | "identity.retryOperation"
  | "identity.scheduleOccurrence"
  | "instant.is"
  | "instant.assert"
  | "retry.validate"
  | "control.write"
  | "canonical.assertProjection"
  | "taskSupport.copyStrings"
  | "taskSupport.assertHook"
  | "taskSupport.isSchema"
  | "taskSupport.hasOwn"
  | "taskSupport.isRecord"
  | "taskObservation.copy"
  | "migration.diagnose"
  | "migration.legacy"
  | "authorization.authorize"
  | "authorization.grant"
  | "authorization.operation"
  | "server.readManifest"
  | "server.run"
  | "server.runtimeOptions"
  | "capability.assert"
  | "capability.validateReport"
  | "adapter.assertMethods"
  | "authorization.projectSnapshot"
  | "authorization.projectPage"
  | "adapter.assertRuntime"
  | "adapter.isRuntime"
  | "runtime.create"
  | "runtime.current"
  | "runtime.require"
  | "runtime.validateManifest"
  | "runtime.runIn"
  | "serviceOptions.validate"
  | "serviceOptions.serialize"
  | "serviceOptions.deserialize"
  | "serviceOptions.assertSupported"
  | "submission.write"
  | "submission.prepare"
  | "submission.prepareCanonical"
  | "submission.createPipeline"
  | "submission.submitTask"
  | "submission.submitJob"
  | "submission.submitCanonical"
  | "schedule.createControls"
  | "schedule.list"
  | "schedule.get"
  | "schedule.write"
  | "control.create"
  | "control.get"
  | "control.list"
  | "control.observe"
  | "control.cancel"
  | "control.retry"
  | "control.result"
  | "legacy.defineJob"
  | "authorization.createCursor"
  | "authorization.readCursor"
  | "runLocator.create"
  | "runLocator.namespaceHash"
  | "runLocator.validateKeyRing"
  | "runLocator.verify"
  | "runLocator.rotate"
  | "runLocator.routerLoad"
  | "runLocator.routerRegister"
  | "runLocator.routerSnapshot"
  | "runLocator.routerPersist"
  | "runLocator.routerRoute"
  | "trigger.copyOptions"
  | "trigger.resultOptions"
  | "schedule.copyDefinitions"
  | "binding.resolve"
  | "runtime.resolveBinding"
  | "client.runAbortable"
  | "client.create"
  | "client.enqueue"
  | "task.createProgressEmitter"
  | "task.createStreamEmitter"
  | "task.emitProgress"
  | "task.emitStream"
  | "schedule.reconcile"
  | "schedule.owner"
  | "schedule.operationId"
  | "schedule.writeRecovery"
  | "control.pollResult"
  | "taskWire.encodeJob"
  | "taskWire.encodeInput"
  | "taskWire.encodeOutput"
  | "taskWire.decodeJob"
  | "taskWire.validateInput"
  | "taskWire.validateCanonicalInput"
  | "taskWire.validateOutput"
  | "taskWire.validateCanonicalOutput"
  | "job.define"
  | "job.isDescriptor"
  | "job.assertDescriptor"
  | "task.define"
  | "task.isDescriptor"
  | "task.assertDescriptor"
  | "client.resolveProvider"
  | "client.parseInput"
  | "client.assertOptions"
  | "client.assertOptionalText"
  | "client.normalizeResult"
  | "client.notify"
  | "client.resolveCorrelation"
  | "taskValidation.assertSchema"
  | "taskValidation.normalizeVersion"
  | "taskValidation.inputWire"
  | "taskValidation.canonicalSchema"
  | "taskValidation.canonicalStreams"
  | "taskValidation.retry"
  | "taskValidation.dependencies"
  | "taskValidation.errors"
  | "taskValidation.streams"
  | "taskValidation.duration"
  | "taskPolicy.utf8Bytes"
  | "taskPolicy.boundedString"
  | "taskPolicy.fieldName"
  | "taskPolicy.memoryBytes"
  | "taskPolicy.scalarKey"
  | "taskPolicy.tags"
  | "taskPolicy.resources"
  | "taskPolicy.concurrency"
  | "taskPolicy.logging"
  | "taskPolicy.retryDelay"
  | "jobValidation.admission"
  | "jobValidation.client"
  | "submission.admission"
  | "submission.submitPrepared"
  | "control.observeSetup"
  | "control.observeNext"
  | "controlSupport.context"
  | "controlSupport.requireMethod"
  | "controlSupport.operationId"
  | "controlSupport.cancelReceipt"
  | "controlSupport.retryReceipt"
  | "controlSupport.isUnknown"
  | "controlSupport.unknownKey"
  | "controlSupport.unknownRecovery"
  | "controlSupport.isTerminal"
  | "controlSupport.timeout"
  | "controlSupport.isRecord"
  | "submissionSupport.error"
  | "submissionSupport.receipt"
  | "submissionSupport.envelope"
  | "submissionSupport.isUnknown"
  | "submissionSupport.isRecord"
  | "submissionSupport.idempotency"
  | "submissionSupport.boundedKey"
  | "submissionSupport.scheduledTime"
  | "submissionSupport.correlation"
  | "submissionSupport.propagation"
  | "submissionSupport.parentRun"
  | "submissionSupport.hashWire"
  | "binding.selectProfile"
  | "binding.taskId";

/** Substitutable observer used by jobs Effect operations.
 * @example
 * const observer: JobsTelemetryService = { observe: (_name, effect) => effect };
 */
export interface JobsTelemetryService {
  /** Surrounds an operation while preserving its success and error channels.
   * @param operation - A stable operation name.
   * @param effect - The operation to observe.
   * @returns The observed Effect with unchanged success and error types.
   * @example observer.observe("duration.toMillis", Effect.succeed(1000));
   */
  readonly observe: <A, E, R>(
    operation: JobsOperation,
    effect: Effect.Effect<A, E, R>,
  ) => Effect.Effect<A, E, R>;
}
