import { createHash } from "node:crypto";
import {
  AGENT_PROTOCOL_CAPABILITY,
  canonicalJson,
  CONTRACT_VERSION,
  type JsonValue,
} from "@relkit/contracts";
import type { AgentNode, ApplicationGraph, ChannelNode } from "@relkit/graph";
import { agentContractType } from "./generate-agent-contract-types.js";
import { clientRoutes, type ClientRoute } from "./generate-types.js";
import { schemaType } from "./generate-schema.js";
export function publicFingerprint(graph: ApplicationGraph): string {
  const source = canonicalJson(publicManifest(graph) as unknown as JsonValue);
  return `sha256:${createHash("sha256").update(source).digest("hex")}`;
}

export function generateClientManifest(graph: ApplicationGraph): string {
  return `${canonicalJson({ ...publicManifest(graph), publicFingerprint: publicFingerprint(graph) } as unknown as JsonValue)}\n`;
}

export function generateClientRegistryFromDocument(document: Record<string, unknown>): string {
  const procedures = Array.isArray(document.procedures) ? document.procedures : [];
  const entries = procedures.flatMap((value) => {
    if (!isRecord(value) || typeof value.name !== "string") return [];
    const route = isRecord(value.route) ? value.route : {};
    const output = isRecord(value.output) ? value.output : {};
    const stream = output.kind === "stream";
    const item = stream ? output.item : value.output;
    const operation = route.operation === "mutation" ? "mutation" : "query";
    const type = stream
      ? `import("@relkit/client/react").ClientStreamContract<${schemaType(value.input)}, ${schemaType(item)}, Error> & { readonly operation: ${JSON.stringify(operation)} }`
      : `import("@relkit/client/react").ClientRouteContract<${schemaType(value.input)}, ${schemaType(value.output)}, Error> & { readonly operation: ${JSON.stringify(operation)} }`;
    const selector = typeof value.selector === "string" ? [value.selector] : [];
    return [...new Set([value.name, ...selector])].map(
      (name) => `    readonly ${JSON.stringify(name)}: ${type};`,
    );
  });
  const channels = arrayRecords(document.channels).flatMap((channel) =>
    typeof channel.id === "string"
      ? [`    readonly ${JSON.stringify(channel.id)}: ${channelDocumentType(channel)};`]
      : [],
  );
  const agents = arrayRecords(document.agents).flatMap((agent) =>
    typeof agent.id === "string"
      ? [`    readonly ${JSON.stringify(agent.id)}: ${agentDocumentType(agent)};`]
      : [],
  );
  return registrySource(entries, channels, agents);
}
export function generateClientRegistry(graph: ApplicationGraph): string {
  const entries = clientRoutes(graph).flatMap((route) => {
    const type = registryType(route);
    const names = [route.trigger.id, selector(route)];
    return [...new Set(names)]
      .sort()
      .map((name) => `    readonly ${JSON.stringify(name)}: ${type};`);
  });
  const channels = publicChannels(graph).map(
    (channel) => `    readonly ${JSON.stringify(channel.id)}: ${channelRegistryType(channel)};`,
  );
  const agents = publicAgents(graph).map(
    (agent) => `    readonly ${JSON.stringify(agent.id)}: ${agentRegistryType(agent)};`,
  );
  return registrySource(entries, channels, agents);
}
function registrySource(entries: string[], channels: string[], agents: string[]): string {
  return [
    "/* generated by @relkit/client-generator; do not edit */",
    'declare module "@relkit/client/react" {',
    "  interface ClientRegistry {",
    ...entries,
    "  }",
    "  interface ChannelRegistry {",
    ...channels,
    "  }",
    "  interface AgentRegistry {",
    ...agents,
    "  }",
    "}",
    "export {};",
    "",
  ].join("\n");
}
function channelRegistryType(channel: ChannelNode): string {
  const events = Object.entries(channel.events)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, value]) => `${JSON.stringify(name)}: ${schemaType(value)}`)
    .join("; ");
  const presence =
    channel.presence === "count"
      ? 'import("@relkit/client/react").CountPresence'
      : isRecord(channel.presence) && channel.presence.member !== undefined
        ? `import("@relkit/client/react").MemberPresence<${schemaType(channel.presence.member)}>`
        : "never";
  return `import("@relkit/client/react").ClientChannelContract<${schemaType(channel.params)}, { ${events} }, ${presence}>`;
}

function agentRegistryType(agent: AgentNode): string {
  return agentContractType(agent);
}

function registryType(route: ClientRoute): string {
  const input = schemaType(route.target.input);
  const errors = route.responses
    .filter((entry) => entry.kind === "error")
    .map((entry) => schemaType(entry.schema));
  const error = errors.length === 0 ? "Error" : errors.join(" | ");
  const operation =
    route.trigger.config.client === false
      ? "query"
      : (route.trigger.config.client?.operation ?? "query");
  const output = route.target.output as Record<string, unknown>;
  if (output.kind === "stream") {
    return `import("@relkit/client/react").ClientStreamContract<${input}, ${schemaType(output.item)}, ${error}> & { readonly operation: ${JSON.stringify(operation)} }`;
  }
  return `import("@relkit/client/react").ClientRouteContract<${input}, ${schemaType(output)}, ${error}> & { readonly operation: ${JSON.stringify(operation)} }`;
}

export function publicManifest(graph: ApplicationGraph): object {
  return {
    protocol: "relkit.client-manifest",
    version: CONTRACT_VERSION,
    capabilities: { agentStream: AGENT_PROTOCOL_CAPABILITY },
    routes: clientRoutes(graph).map((route) => ({
      routeId: route.trigger.id,
      selector: selector(route),
      functionId: route.target.id,
      operation:
        route.trigger.config.client === false
          ? "query"
          : (route.trigger.config.client?.operation ?? "query"),
      stream:
        route.target.output !== null &&
        typeof route.target.output === "object" &&
        !Array.isArray(route.target.output) &&
        (route.target.output as Record<string, unknown>).kind === "stream",
    })),
    channels: publicChannels(graph).map((node) => ({
      id: node.id,
      client: node.client,
      params: node.params,
      events: node.events,
      presence: node.presence ?? null,
    })),
    agents: publicAgents(graph).map((node) => ({
      id: node.id,
      client: node.client,
      controls: node.controls ?? [],
      chat: node.chat ?? null,
      input: node.input,
      output: node.output,
      ...(node.workflow === undefined ? {} : { workflow: node.workflow }),
      ...(node.clientContract === undefined ? {} : { clientContract: node.clientContract }),
    })),
  };
}

function channelDocumentType(channel: Record<string, unknown>): string {
  const events = isRecord(channel.events)
    ? Object.entries(channel.events)
        .map(([name, schema]) => `${JSON.stringify(name)}: ${schemaType(schema)}`)
        .join("; ")
    : "";
  const presence =
    channel.presence === "count"
      ? 'import("@relkit/client/react").CountPresence'
      : isRecord(channel.presence) && channel.presence.member !== undefined
        ? `import("@relkit/client/react").MemberPresence<${schemaType(channel.presence.member)}>`
        : "never";
  return `import("@relkit/client/react").ClientChannelContract<${schemaType(channel.params)}, { ${events} }, ${presence}>`;
}

function agentDocumentType(agent: Record<string, unknown>): string {
  return agentContractType(agent);
}

function arrayRecords(value: unknown): Record<string, unknown>[] {
  return Array.isArray(value) ? value.filter(isRecord) : [];
}

function publicChannels(graph: ApplicationGraph): readonly ChannelNode[] {
  return graph.nodes.filter(
    (node): node is ChannelNode => node.kind === "channel" && node.client !== "internal",
  );
}

function publicAgents(graph: ApplicationGraph): readonly AgentNode[] {
  return graph.nodes.filter(
    (node): node is AgentNode => node.kind === "agent" && node.client !== undefined,
  );
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function selector(route: ClientRoute): string {
  return `${route.trigger.config.method} ${route.trigger.config.path}`;
}
