import type { ApplicationGraph, JobProcedureSource } from "./generate-job-registry-render.types.js";
import { Effect } from "effect";
import { jobProcedureCalculations } from "./generate-job-procedures.js";
import {
  jobClientRegistryEntriesCore,
  jobRegistryTypeCore,
} from "./generate-job-registry-calculations.js";

/** Assembles job registry augmentation from normalized job sources.
 * @param sources - Ordered public job sources.
 * @returns An Effect yielding registry source; it has no expected failure.
 * @example Effect.runSync(generateJobRegistryFromSources([]));
 */
export const generateJobRegistryFromSources = Effect.fnUntraced(function* (
  sources: readonly JobProcedureSource[],
) {
  const jobs: string[] = [];
  const procedures: string[] = [];
  for (const source of sources) {
    const type = yield* jobRegistryTypeCore(source);
    jobs.push(`    readonly ${JSON.stringify(source.name)}: ${type};`);
    procedures.push(...(yield* jobClientRegistryEntriesCore(source)));
  }
  return [
    "/* generated by @relkit/client-generator; do not edit */",
    'declare module "@relkit/client/jobs" {',
    "  interface JobRegistry {",
    ...jobs,
    "  }",
    "}",
    'declare module "@relkit/client/react" {',
    "  interface ClientRegistry {",
    ...procedures,
    "  }",
    "}",
    "export {};",
    "",
  ].join("\n");
});

/** Builds a job registry from exposed graph jobs.
 * @param graph - Validated application graph.
 * @returns An Effect yielding registry source; it has no expected failure.
 * @example Effect.runSync(generateJobRegistryCore(graph));
 */
export const generateJobRegistryCore = Effect.fnUntraced(function* (graph: ApplicationGraph) {
  const sources = yield* jobProcedureCalculations.graphSourcesEffect(graph);
  return yield* generateJobRegistryFromSources(sources);
});

/** Builds a job registry from serialized job sources.
 * @param value - Unknown job document list.
 * @returns An Effect yielding registry source; it has no expected failure.
 * @example Effect.runSync(generateJobRegistryFromDocumentCore([]));
 */
export const generateJobRegistryFromDocumentCore = Effect.fnUntraced(function* (value: unknown) {
  const sources = yield* jobProcedureCalculations.documentSourcesEffect(value);
  return yield* generateJobRegistryFromSources(sources);
});
