import { canonicalJson, CONTRACT_VERSION, type JsonValue } from "@relkit/contracts";
import type { ApplicationGraph } from "@relkit/graph";
import { clientRoutes } from "./generate-types.js";
import { schemaType } from "./generate-schema.js";

export function generateContract(graph: ApplicationGraph): string {
  return generateContractFromDocument(
    clientRoutes(graph).map((route) => ({
      name: route.trigger.id,
      input: route.target.input,
      output: route.target.output,
      errors: errors(route.target.errors),
    })),
  );
}

export interface ContractProcedureDocument {
  readonly name: string;
  readonly input: unknown;
  readonly output: unknown;
  readonly errors: readonly { readonly id: string; readonly schema: unknown }[];
}

export function generateContractFromDocument(
  procedures: readonly ContractProcedureDocument[],
): string {
  const entries = [...procedures]
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((procedure) => {
      const errorMap = procedure.errors.map(
        (entry) => `${JSON.stringify(entry.id)}: { data: schema<${schemaType(entry.schema)}>() }`,
      );
      const builder = [
        "oc",
        errorMap.length === 0 ? "" : `.errors({ ${errorMap.join(", ")} })`,
        `.input(schema<${schemaType(procedure.input)}>())`,
        `.output(schema<${schemaType(procedure.output)}>())`,
      ].join("");
      return `  ${JSON.stringify(procedure.name)}: ${builder},`;
    });
  return [
    "/* generated by @relkit/client-generator; do not edit */",
    'import { oc } from "@orpc/contract";',
    "",
    "function schema<Value>() {",
    "  return {",
    '    "~standard": {',
    "      version: 1 as const,",
    '      vendor: "relkit-contract",',
    "      types: undefined as unknown as { input: Value; output: Value },",
    "      validate: (value: unknown) => ({ value: value as Value }),",
    "    },",
    "  };",
    "}",
    "",
    "export const contract = {",
    ...entries,
    "} as const;",
    "export default contract;",
    "",
    'declare module "@relkit/client" {',
    "  interface DefaultContractRegistry {",
    "    readonly contract: typeof contract;",
    "  }",
    "}",
    "",
  ].join("\n");
}

export function generateClientContractDocument(graph: ApplicationGraph, graphHash: string): string {
  const procedures = clientRoutes(graph).map((route) => ({
    name: route.trigger.id,
    routeId: route.trigger.id,
    functionId: route.target.id,
    input: route.target.input,
    output: route.target.output,
    errors: errorDocuments(route.target.errors, route.responses),
    route: {
      method: route.trigger.config.method,
      path: route.trigger.config.path,
    },
  }));
  return `${canonicalJson({
    protocol: "relkit.client-contract",
    version: CONTRACT_VERSION,
    graphHash,
    procedures,
  } as unknown as JsonValue)}\n`;
}

function errorDocuments(
  value: unknown,
  responses: readonly { readonly errorId?: string; readonly status: number }[],
): JsonValue {
  return errors(value).map((entry) => ({
    id: entry.id,
    schema: entry.schema as JsonValue,
    status: responses.find((response) => response.errorId === entry.id)?.status ?? 500,
  })) as JsonValue;
}

function errors(value: unknown): { readonly id: string; readonly schema: unknown }[] {
  return (Array.isArray(value) ? value : []).flatMap((entry) => {
    if (!isRecord(entry) || typeof entry.id !== "string") return [];
    const data =
      isRecord(entry.data) && isRecord(entry.data.jsonSchema) ? entry.data.jsonSchema : entry.data;
    return [{ id: entry.id, schema: data ?? {} }];
  });
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}
