import type { ApplicationGraph } from "@relkit/graph";
import { schemaType } from "./generate-schema.js";
import {
  jobFailureType,
  jobFieldsType,
  jobSnapshotType,
  jobStreamItemType,
} from "./generate-job-types.js";
import {
  jobProcedureSources,
  jobProcedureSourcesFromDocument,
  type JobProcedureSource,
} from "./generate-job-procedures.js";

/** Generates the sole browser-safe JobRegistry plus React selector entries. */
export function generateJobRegistry(graph: ApplicationGraph): string {
  return generateJobRegistryFromSources(jobProcedureSources(graph));
}

export function generateJobRegistryFromDocument(value: unknown): string {
  return generateJobRegistryFromSources(jobProcedureSourcesFromDocument(value));
}

export function jobRegistryType(source: JobProcedureSource): string {
  return `import("@relkit/client/jobs").JobContract<${JSON.stringify(source.name)}, ${JSON.stringify(source.jobId)}, ${schemaType(source.input)}, ${schemaType(source.output)}, ${jobFailureType(source.errors)}, ${schemaType(source.progress)}, ${streamRecordType(source)}, ${operationsType(source)}, ${jobFieldsType(source.fields)}>`;
}

export function jobClientRegistryEntries(source: JobProcedureSource): readonly string[] {
  return source.operations.map((operation) => {
    const selector =
      operation === "trigger"
        ? `jobs.${source.name}.trigger`
        : `jobs.${source.name}.runs.${operation}`;
    const type = jobProcedureType(source, operation);
    return `    readonly ${JSON.stringify(selector)}: ${type};`;
  });
}

function generateJobRegistryFromSources(sources: readonly JobProcedureSource[]): string {
  const jobs = sources.map(
    (source) => `    readonly ${JSON.stringify(source.name)}: ${jobRegistryType(source)};`,
  );
  const procedures = sources.flatMap(jobClientRegistryEntries);
  return [
    "/* generated by @relkit/client-generator; do not edit */",
    'declare module "@relkit/client/jobs" {',
    "  interface JobRegistry {",
    ...jobs,
    "  }",
    "}",
    'declare module "@relkit/client/react" {',
    "  interface ClientRegistry {",
    ...procedures,
    "  }",
    "}",
    "export {};",
    "",
  ].join("\n");
}

function jobProcedureType(
  source: JobProcedureSource,
  operation: JobProcedureSource["operations"][number],
): string {
  const error = jobFailureType(source.errors);
  if (operation === "trigger") {
    return `import("@relkit/client/jobs").JobProcedureContract<${triggerInputType(source)}, import("@relkit/contracts/jobs").RunHandle, ${error}> & { readonly operation: "mutation" }`;
  }
  if (operation === "get") {
    return `import("@relkit/client/jobs").JobProcedureContract<${getInputType}, ${jobSnapshotType(source)}, ${error}> & { readonly operation: "query" }`;
  }
  if (operation === "list") {
    return `import("@relkit/client/jobs").JobProcedureContract<${listInputType}, import("@relkit/contracts/jobs").RunPage<${jobSnapshotType(source)}>, ${error}> & { readonly operation: "query" }`;
  }
  if (operation === "watch") {
    return `import("@relkit/client/jobs").JobStreamProcedureContract<${watchInputType}, import("@relkit/contracts/jobs").RunWatchFrame<${jobSnapshotType(source)}>, ${error}> & { readonly operation: "query" }`;
  }
  if (operation === "stream") {
    return `import("@relkit/client/jobs").JobStreamProcedureContract<${streamInputType(source)}, import("@relkit/contracts/jobs").NamedStreamFrame<${jobStreamItemType(source)}>, ${error}> & { readonly operation: "query" }`;
  }
  if (operation === "cancel") {
    return `import("@relkit/client/jobs").JobProcedureContract<${cancelInputType}, import("@relkit/contracts/jobs").RunCancellationReceipt, ${error}> & { readonly operation: "mutation" }`;
  }
  return `import("@relkit/client/jobs").JobProcedureContract<${retryInputType}, import("@relkit/contracts/jobs").RunRetryReceipt, ${error}> & { readonly operation: "mutation" }`;
}

function streamRecordType(source: JobProcedureSource): string {
  const streams = isRecord(source.streams) ? source.streams : {};
  const entries = source.streamNames.map(
    (name) => `${JSON.stringify(name)}: ${schemaType(streams[name])}`,
  );
  return entries.length === 0 ? "Readonly<Record<never, never>>" : `{ ${entries.join("; ")} }`;
}

function operationsType(source: JobProcedureSource): string {
  return `readonly [${source.operations.map((operation) => JSON.stringify(operation)).join(", ")}]`;
}

function triggerInputType(source: JobProcedureSource): string {
  return `{ readonly input: ${schemaType(source.input)}; readonly options?: import("@relkit/client/jobs").JobTriggerOptions; readonly expectedIdentity?: import("@relkit/contracts").ExpectedClientIdentity }`;
}

const getInputType =
  '{ readonly runId: string; readonly expectedIdentity?: import("@relkit/contracts").ExpectedClientIdentity }';
const listInputType =
  '{ readonly query?: import("@relkit/client/jobs").JobListQuery; readonly expectedIdentity?: import("@relkit/contracts").ExpectedClientIdentity }';
const watchInputType =
  '{ readonly runId: string; readonly after?: string; readonly expectedIdentity?: import("@relkit/contracts").ExpectedClientIdentity }';
const cancelInputType =
  '{ readonly runId: string; readonly operationId: import("@relkit/contracts").OperationId | string; readonly reason?: string; readonly expectedIdentity?: import("@relkit/contracts").ExpectedClientIdentity }';
const retryInputType =
  '{ readonly runId: string; readonly operationId: import("@relkit/contracts").OperationId | string; readonly expectedIdentity?: import("@relkit/contracts").ExpectedClientIdentity }';

function streamInputType(source: JobProcedureSource): string {
  const names = source.streamNames.map((name) => JSON.stringify(name)).join(" | ") || "never";
  return `{ readonly runId: string; readonly name: ${names}; readonly after?: string; readonly expectedIdentity?: import("@relkit/contracts").ExpectedClientIdentity }`;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}
