import { createHash } from "node:crypto";
import {
  AGENT_PROTOCOL_CAPABILITY,
  canonicalJson,
  CONTRACT_VERSION,
  type JsonValue,
} from "@relkit/contracts";
import { JOBS_PROTOCOL, JOBS_PROTOCOL_VERSION } from "@relkit/contracts/jobs";
import type { AgentNode, ApplicationGraph, ChannelNode } from "@relkit/graph";
import { agentContractType } from "./generate-agent-contract-types.js";
import { clientRoutes, type ClientRoute } from "./generate-types.js";
import { schemaType } from "./generate-schema.js";
import { jobProcedureDocument, jobProcedureSources } from "./generate-job-procedures.js";
import { generateJobRegistry, generateJobRegistryFromDocument } from "./generate-job-registry.js";
import { publicManifest } from "./generate-public-manifest.js";
import {
  agentDocumentType,
  arrayRecords,
  channelDocumentType,
  isRecord,
  publicAgents,
  publicChannels,
  selector,
} from "./generate-registry-support.js";
export { publicManifest } from "./generate-public-manifest.js";
export function publicFingerprint(graph: ApplicationGraph): string {
  const source = canonicalJson(publicManifest(graph) as unknown as JsonValue);
  return `sha256:${createHash("sha256").update(source).digest("hex")}`;
}

export function generateClientManifest(graph: ApplicationGraph): string {
  return `${canonicalJson({ ...publicManifest(graph), publicFingerprint: publicFingerprint(graph) } as unknown as JsonValue)}\n`;
}

export function generateClientRegistryFromDocument(document: Record<string, unknown>): string {
  const procedures = Array.isArray(document.procedures) ? document.procedures : [];
  const entries = procedures.flatMap((value) => {
    if (!isRecord(value) || typeof value.name !== "string") return [];
    const route = isRecord(value.route) ? value.route : {};
    const output = isRecord(value.output) ? value.output : {};
    const stream = output.kind === "stream";
    const item = stream ? output.item : value.output;
    const operation = route.operation === "mutation" ? "mutation" : "query";
    const type = stream
      ? `import("@relkit/client/react").ClientStreamContract<${schemaType(value.input)}, ${schemaType(item)}, Error> & { readonly operation: ${JSON.stringify(operation)} }`
      : `import("@relkit/client/react").ClientRouteContract<${schemaType(value.input)}, ${schemaType(value.output)}, Error> & { readonly operation: ${JSON.stringify(operation)} }`;
    const selector = typeof value.selector === "string" ? [value.selector] : [];
    return [...new Set([value.name, ...selector])].map(
      (name) => `    readonly ${JSON.stringify(name)}: ${type};`,
    );
  });
  const channels = arrayRecords(document.channels).flatMap((channel) =>
    typeof channel.id === "string"
      ? [`    readonly ${JSON.stringify(channel.id)}: ${channelDocumentType(channel)};`]
      : [],
  );
  const agents = arrayRecords(document.agents).flatMap((agent) =>
    typeof agent.id === "string"
      ? [`    readonly ${JSON.stringify(agent.id)}: ${agentDocumentType(agent)};`]
      : [],
  );
  const jobs = Array.isArray(document.jobs) ? document.jobs : [];
  return [
    registrySource(entries, channels, agents),
    ...(jobs.length === 0 ? [] : [generateJobRegistryFromDocument(jobs)]),
  ].join("");
}
export function generateClientRegistry(graph: ApplicationGraph): string {
  const entries = clientRoutes(graph).flatMap((route) => {
    const type = registryType(route);
    const names = [route.trigger.id, selector(route)];
    return [...new Set(names)]
      .sort()
      .map((name) => `    readonly ${JSON.stringify(name)}: ${type};`);
  });
  const channels = publicChannels(graph).map(
    (channel) => `    readonly ${JSON.stringify(channel.id)}: ${channelRegistryType(channel)};`,
  );
  const agents = publicAgents(graph).map(
    (agent) => `    readonly ${JSON.stringify(agent.id)}: ${agentRegistryType(agent)};`,
  );
  const jobs = jobProcedureSources(graph);
  return [
    registrySource(entries, channels, agents),
    ...(jobs.length === 0 ? [] : [generateJobRegistry(graph)]),
  ].join("");
}
function registrySource(entries: string[], channels: string[], agents: string[]): string {
  return [
    "/* generated by @relkit/client-generator; do not edit */",
    'declare module "@relkit/client/react" {',
    "  interface ClientRegistry {",
    ...entries,
    "  }",
    "  interface ChannelRegistry {",
    ...channels,
    "  }",
    "  interface AgentRegistry {",
    ...agents,
    "  }",
    "}",
    "export {};",
    "",
  ].join("\n");
}
function channelRegistryType(channel: ChannelNode): string {
  const events = Object.entries(channel.events)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, value]) => `${JSON.stringify(name)}: ${schemaType(value)}`)
    .join("; ");
  const presence =
    channel.presence === "count"
      ? 'import("@relkit/client/react").CountPresence'
      : isRecord(channel.presence) && channel.presence.member !== undefined
        ? `import("@relkit/client/react").MemberPresence<${schemaType(channel.presence.member)}>`
        : "never";
  return `import("@relkit/client/react").ClientChannelContract<${schemaType(channel.params)}, { ${events} }, ${presence}>`;
}

function agentRegistryType(agent: AgentNode): string {
  return agentContractType(agent);
}

function registryType(route: ClientRoute): string {
  const input = schemaType(route.target.input);
  const errors = route.responses
    .filter((entry) => entry.kind === "error")
    .map((entry) => schemaType(entry.schema));
  const error = errors.length === 0 ? "Error" : errors.join(" | ");
  const operation =
    route.trigger.config.client === false
      ? "query"
      : (route.trigger.config.client?.operation ?? "query");
  const output = route.target.output as Record<string, unknown>;
  if (output.kind === "stream") {
    return `import("@relkit/client/react").ClientStreamContract<${input}, ${schemaType(output.item)}, ${error}> & { readonly operation: ${JSON.stringify(operation)} }`;
  }
  return `import("@relkit/client/react").ClientRouteContract<${input}, ${schemaType(output)}, ${error}> & { readonly operation: ${JSON.stringify(operation)} }`;
}
