import type { ApplicationGraph } from "./generate.types.js";
import { Effect } from "effect";
import { makeGeneratorOperation } from "./generator-operation.js";
/** Generates the default typed client entrypoint backed by the generated oRPC contract.
 * @param graph - Application graph supplied by the compiler.
 * @returns An Effect yielding fixed client source; it has no expected failure.
 * @example Effect.runSync(generateClientEffect(graph));
 */
const generateClientCore = Effect.fnUntraced(function* (graph: ApplicationGraph) {
  void graph;
  return [
    "/* generated by @relkit/client-generator; do not edit */",
    'export { createClient, ORPCError } from "@relkit/client";',
    'export { contract } from "./contract.js";',
    "",
  ].join("\n");
});
const generateClientOperation = makeGeneratorOperation("generateClient", generateClientCore);
/** Renders the client entrypoint that exposes the generated oRPC contract.
 * @param graph - Application graph to render.
 * @returns An Effect with the rendered result and no expected typed failures.
 * @example Effect.runSync(generateClientEffect(graph));
 */
export const generateClientEffect = generateClientOperation.effect;
/** Renders the client entrypoint for synchronous compiler callers.
 * @param graph - Application graph to render.
 * @returns The rendered result.
 * @throws If malformed trusted input causes a defect.
 * @example generateClient(graph);
 */
export const generateClient = generateClientOperation.run;
/** Generates the TypeScript client entrypoint through the same Effect adapter.
 * @param graph - Application graph supplied by the compiler.
 * @returns Generated TypeScript source.
 * @throws If malformed trusted graph input causes a defect.
 * @example generateClientTypeScript(graph);
 */
export const generateClientTypeScript = generateClient;
/** Effect alias for compiler callers that name the TypeScript output explicitly.
 * @param graph - Application graph supplied by the compiler.
 * @returns An Effect with generated TypeScript source and no expected failures.
 * @example Effect.runSync(generateClientTypeScriptEffect(graph));
 */
export const generateClientTypeScriptEffect = generateClientEffect;
