import type { ApplicationGraph } from "@relkit/graph";

/** Generates the default typed client entrypoint backed by the generated oRPC contract. */
export function generateClient(graph: ApplicationGraph): string {
  void graph;
  return [
    "/* generated by @relkit/client-generator; do not edit */",
    'export { createClient, ORPCError } from "@relkit/client";',
    'export { contract } from "./contract.js";',
    "",
  ].join("\n");
}

/** Alias with an explicit output-format name for compiler callers. */
export const generateClientTypeScript = generateClient;
