import type {
  JobProcedureSource,
  ContractProcedureDocument,
} from "./generate-contract-from-document.types.js";
import { Effect } from "effect";
import { makeGeneratorOperation } from "./generator-operation.js";
import { schemaCalculations } from "./generate-schema.js";
import { jobProcedureCalculations } from "./generate-job-procedures.js";
/** Sorts procedure documents and renders the oRPC contract source.
 * @param procedures - Public procedure documents.
 * @param additionalEntries - Agent procedure entries.
 * @param jobs - Public job sources.
 * @returns An Effect yielding generated source; it has no expected failure.
 * @example Effect.runSync(contractFromDocumentCalculations.renderEffect([]));
 */
function generateContractFromDocumentCore(
  procedures: readonly ContractProcedureDocument[],
  additionalEntries: readonly string[] = [],
  jobs: readonly JobProcedureSource[] = [],
): Effect.Effect<string> {
  return Effect.gen(function* () {
    const entries: string[] = [];
    for (const procedure of [...procedures].sort((left, right) =>
      left.name.localeCompare(right.name),
    )) {
      const errorMap: string[] = [];
      for (const entry of procedure.errors) {
        const schema = yield* schemaCalculations.typeEffect(entry.schema);
        errorMap.push(`${JSON.stringify(entry.id)}: { data: schema<${schema}>() }`);
      }
      const input = yield* schemaCalculations.typeEffect(procedure.input);
      const output = yield* schemaCalculations.typeEffect(procedure.output);
      const builder = [
        "oc",
        errorMap.length === 0 ? "" : `.errors({ ${errorMap.join(", ")} })`,
        `.input(schema<${input}>())`,
        `.output(schema<${output}>())`,
      ].join("");
      entries.push(`  ${JSON.stringify(procedure.name)}: ${builder},`);
    }
    return [
      "/* generated by @relkit/client-generator; do not edit */",
      'import { oc } from "@orpc/contract";',
      "",
      "function schema<Value>() {",
      "  return {",
      '    "~standard": {',
      "      version: 1 as const,",
      '      vendor: "relkit-contract",',
      "      types: undefined as unknown as { input: Value; output: Value },",
      "      validate: (value: unknown) => ({ value: value as Value }),",
      "    },",
      "  };",
      "}",
      "",
      "export const contract = {",
      ...entries,
      ...(yield* jobProcedureCalculations.entriesEffect(jobs)),
      ...additionalEntries,
      "} as const;",
      "export default contract;",
      "",
      'declare module "@relkit/client" {',
      "  interface DefaultContractRegistry {",
      "    readonly contract: typeof contract;",
      "  }",
      "}",
      "",
    ].join("\n");
  });
}
const operation = makeGeneratorOperation(
  "generateContractFromDocument",
  generateContractFromDocumentCore,
);
/** Renders an oRPC contract module from procedure documents.
 * @param procedures - Procedure documents to render.
 * @param additionalEntries - Additional procedure entries.
 * @param jobs - Job sources to include.
 * @returns An Effect containing TypeScript source with no expected typed failures.
 * @example Effect.runSync(generateContractFromDocumentEffect([{ name: "orders.get", input: {}, output: {}, errors: [] }]));
 */
export const generateContractFromDocumentEffect = operation.effect;
/** Synchronous contract renderer for compiler compatibility.
 * @param procedures - Procedure documents to render.
 * @param additionalEntries - Additional procedure entries.
 * @param jobs - Job sources to include.
 * @returns Generated TypeScript source.
 * @throws If malformed trusted procedure metadata causes a defect.
 * @example generateContractFromDocument([{ name: "orders.get", input: {}, output: {}, errors: [] }]);
 */
export const generateContractFromDocument = operation.run;
/** Renderer reused inside graph-backed contract generation. @internal */
export const contractFromDocumentCalculations = {
  render: operation.run,
  renderEffect: generateContractFromDocumentCore,
} as const;
