import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { defaultCatalog, type CatalogManifest } from "./catalog-manifest.js";

import type { BuildCatalog } from "./build-catalog.types.js";
export type { BuildCatalog } from "./build-catalog.types.js";

export const drizzlePatchPath = "patches/drizzle-orm.patch";
/**
 * Derives the canonical Drizzle registration while preserving unrelated patches.
 * @param manifest - Root manifest containing the authoritative Drizzle catalog pin.
 * @returns Exact package-version patch registrations.
 */
export function patchRegistrations(manifest: CatalogManifest): Record<string, string> {
  const version = defaultCatalog(manifest)["drizzle-orm"];
  if (version === undefined) throw new Error("The default catalog must pin drizzle-orm.");
  const existing = manifest.patchedDependencies ?? {};
  if (typeof existing !== "object" || existing === null || Array.isArray(existing))
    throw new Error("patchedDependencies must be an object.");
  const result: Record<string, string> = {};
  for (const [name, path] of Object.entries(existing)) {
    if (typeof path !== "string") throw new Error(`Invalid patch path for ${name}`);
    if (!name.startsWith("drizzle-orm@")) result[name] = path;
  }
  result[`drizzle-orm@${version}`] = drizzlePatchPath;
  return result;
}

/**
 * Snapshots shared pins, the stable Effect cohort, and portable patch identity.
 * @param root - Repository root containing the canonical patch asset.
 * @param manifest - Root package manifest containing the default catalog.
 * @returns Metadata ready to embed in published package manifests.
 * @throws When pins diverge, Effect is not stable, or the patch cannot be read.
 */
export async function buildCatalog(root: string, manifest: CatalogManifest): Promise<BuildCatalog> {
  const dependencies = defaultCatalog(manifest);
  const effectVersion = dependencies.effect;
  if (effectVersion === undefined || !/^\d+\.\d+\.\d+$/.test(effectVersion))
    throw new Error("The default catalog must pin a stable Effect version.");
  for (const [name, version] of Object.entries(dependencies))
    if (name.startsWith("@effect/") && version !== effectVersion)
      throw new Error(`Effect companion version differs: ${name}@${version}`);
  const version = dependencies["drizzle-orm"];
  if (version === undefined) throw new Error("The default catalog must pin drizzle-orm.");
  const hash = createHash("sha256")
    .update(await readFile(join(root, drizzlePatchPath)))
    .digest("hex");
  return {
    dependencies,
    effectVersion,
    patches: {
      "drizzle-orm": {
        version,
        key: `drizzle-orm@${version}`,
        asset: drizzlePatchPath,
        hash,
      },
    },
  };
}

/**
 * Renders native provider identity with literal types derived from the catalog.
 * @param catalog - Resolved catalog snapshot.
 * @returns A generated TypeScript module containing the Effect and SDK literals.
 */
export function nativeBuildCatalogSource(catalog: BuildCatalog): string {
  const sdkVersion = catalog.dependencies["effect-mq"];
  if (sdkVersion === undefined) throw new Error("The default catalog must pin effect-mq.");
  return [
    "// Generated by scripts/sync-release.ts from the root catalog. Do not edit.",
    `export const effectVersion = ${JSON.stringify(catalog.effectVersion)} as const;`,
    `export const effectMqSdk = ${JSON.stringify(`effect-mq@${sdkVersion}`)} as const;`,
    "",
  ].join("\n");
}
