import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { format } from "prettier";
import {
  assertClean,
  bun,
  checkManifests,
  command,
  digest,
  iteratorSkill,
  packages,
  readJson,
  root,
  stable,
  type RecordValue,
} from "./release-check-support.js";
import { packAll, templateInputs } from "./release-check-artifacts.js";

function releaseNotes(data: RecordValue): string {
  const packageRows = (data.packages as RecordValue[])
    .map((item) => {
      const dependencies = Object.entries(item.dependencyFields.dependencies ?? {})
        .map(([name, spec]) => `\`${name}@${spec}\``)
        .join(", ");
      return `| ${item.name} | ${item.version} | ${Object.keys(item.exports).join(", ")} | ${dependencies || "—"} |`;
    })
    .join("\n");
  const artifactRows = (data.artifacts as RecordValue[])
    .map((item) => `| ${item.name} | ${item.file} | \`${item.sha256}\` |`)
    .join("\n");
  const templateRows = (data.templates as RecordValue[])
    .map((item) => `| ${item.name} | ${item.files} | \`${item.sha256}\` |`)
    .join("\n");
  return `# ZSys ${data.version} release candidate

Deterministic release output generated by \`bun run scripts/release-check.ts --write-notes\`.

## Review status

The package, packed-artifact, template, declaration, boundary, checksum, and clean-worktree checks passed. Owner sign-off remains a Gate 16 responsibility.

## Release inputs

- Input fingerprint: \`${data.inputFingerprint}\`
- Packages: ${data.packages.length}
- Templates: ${data.templates.length}
- Package manager: \`${data.packageManager}\`

| Package | Version | Exports | Dependencies |
| --- | --- | --- | --- |
${packageRows}

## Packed artifacts

| Package | Artifact | SHA-256 |
| --- | --- | --- |
${artifactRows}

## Template checksums

| Template | Files | SHA-256 |
| --- | ---: | --- |
${templateRows}

## Verification

- \`bun run build\` passed before packing.
- \`bun run check\` passed for internal imports and scope.
- \`bun run scripts/check-public-declarations.ts\` passed.
- \`bun run scripts/pack-and-smoke-create-zsys.ts\` passed from packed artifacts, including second-generation reproducibility.
- The default release check enforces a clean worktree, excluding only \`${iteratorSkill}\`.
`;
}

async function main(): Promise<void> {
  const writeNotes = process.argv.includes("--write-notes");
  const allow = new Set([iteratorSkill]);
  if (writeNotes)
    [
      "scripts/release-check.ts",
      "scripts/release-check-support.ts",
      "scripts/release-check-artifacts.ts",
      "RELEASE_NOTES.md",
      "openspec/changes/implement-zsys-typescript-poc-v3/tasks.md",
      "openspec/changes/implement-zsys-typescript-poc-v3/PROGRESS.md",
      "openspec/changes/implement-zsys-typescript-poc-v3/DECISIONS.md",
      "openspec/changes/implement-zsys-typescript-poc-v3/BLOCKERS.md",
    ].forEach((path) => allow.add(path));
  await assertClean(allow);
  const items = await packages();
  const rootManifest = await readJson(join(root, "package.json"));
  const { version, summary } = checkManifests(items);
  await command(bun, ["run", "build"]);
  const templates = await templateInputs(version, rootManifest);
  const artifacts = await packAll(items, version);
  await command(bun, ["run", "check"]);
  await command(bun, ["run", "scripts/check-public-declarations.ts"]);
  await command(bun, ["run", "scripts/pack-and-smoke-create-zsys.ts"]);
  const input = {
    version,
    packageManager: rootManifest.packageManager,
    packages: summary,
    templates,
  };
  const data = { ...input, inputFingerprint: digest(JSON.stringify(stable(input))), artifacts };
  const output = await format(releaseNotes(data), { parser: "markdown" });
  const notePath = join(root, "RELEASE_NOTES.md");
  if (writeNotes) await writeFile(notePath, output, "utf8");
  else if ((await readFile(notePath, "utf8")) !== output)
    throw new Error("RELEASE_NOTES.md is stale; rerun with --write-notes and review the diff.");
  await assertClean(allow);
  console.log(
    JSON.stringify(
      {
        protocol: "zsys.release-check",
        version,
        packages: items.length,
        artifacts: artifacts.length,
        templates: templates.length,
        inputFingerprint: data.inputFingerprint,
      },
      null,
      2,
    ),
  );
}

if (import.meta.main) await main();
