import { copyFile, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { format } from "prettier";
import {
  assertClean,
  bun,
  checkManifests,
  command,
  digest,
  iteratorSkill,
  packages,
  readJson,
  root,
  stable,
  type RecordValue,
} from "./release-check-support.js";
import { packAll, templateInputs } from "./release-check-artifacts.js";

export function releaseNotes(data: RecordValue): string {
  const packageRows = (data.packages as RecordValue[])
    .map((item) => {
      const dependencies = Object.entries(item.dependencyFields.dependencies ?? {})
        .map(([name, spec]) => `\`${name}@${spec}\``)
        .join(", ");
      return `| ${item.name} | ${item.version} | ${Object.keys(item.exports).join(", ")} | ${dependencies || "—"} |`;
    })
    .join("\n");
  const templateRows = (data.templates as RecordValue[])
    .map((item) => `| ${item.name} | ${item.files} | \`${item.sha256}\` |`)
    .join("\n");
  return `# RelKit ${data.version} release candidate

Deterministic release output generated by \`bun run scripts/release-check.ts --write-notes\`.

## Review status

The package, packed-artifact, template, declaration, boundary, checksum, and clean-worktree checks passed. Owner sign-off remains required before publication.

## Release inputs

- Input fingerprint: \`${data.inputFingerprint}\`
- Packages: ${data.packages.length}
- Templates: ${data.templates.length}
- Package manager: \`${data.packageManager}\`

| Package | Version | Exports | Dependencies |
| --- | --- | --- | --- |
${packageRows}

## Packed artifacts

The exact tarball hashes and npm integrity values are recorded in the attached
release manifest and checksum files generated by the publication run.

## Template checksums

| Template | Files | SHA-256 |
| --- | ---: | --- |
${templateRows}

## Verification

- \`bun run build\` passed before packing.
- \`bun run check\` passed for internal imports and scope.
- \`bun run scripts/check-public-declarations.ts\` passed.
- \`bun run scripts/pack-and-smoke-create-relkit.ts\` passed from packed artifacts, including second-generation reproducibility.
- The default release check enforces a clean worktree, excluding only \`${iteratorSkill}\`.
`;
}

function option(name: string): string | undefined {
  const index = process.argv.indexOf(name);
  return index === -1 ? undefined : process.argv[index + 1];
}

async function main(): Promise<void> {
  const writeNotes = process.argv.includes("--write-notes");
  const readiness = process.argv.includes("--readiness");
  const allowDirty = process.argv.includes("--allow-dirty");
  const skipBuild = process.argv.includes("--skip-build");
  const configuredOutput = option("--output");
  if (process.argv.includes("--output") && configuredOutput === undefined)
    throw new Error("--output requires a directory");
  const allow = new Set([iteratorSkill]);
  if (writeNotes) allow.add("RELEASE_NOTES.md");
  if (!allowDirty) await assertClean(allow);
  await command(bun, ["run", "scripts/sync-release.ts"]);
  const items = await packages();
  const rootManifest = await readJson(join(root, "package.json"));
  const { version, summary } = checkManifests(items);
  if (!skipBuild) await command(bun, ["run", "build"]);
  await command(bun, ["run", "scripts/secret-scan.ts"]);
  const templates = await templateInputs(version, rootManifest);
  const temporary = configuredOutput === undefined;
  const artifactRoot = configuredOutput
    ? resolve(configuredOutput)
    : await mkdtemp(join(tmpdir(), "relkit-release-artifacts-"));
  try {
    const artifacts = await packAll(items, version, artifactRoot);
    const commit = (await command("git", ["rev-parse", "HEAD"])).trim();
    const input = {
      version,
      packageManager: rootManifest.packageManager,
      packages: summary,
      templates,
    };
    const data = {
      ...input,
      commit,
      inputFingerprint: digest(JSON.stringify(stable(input))),
      artifacts,
    };
    const manifest = {
      protocol: "relkit.release-manifest.v1",
      version,
      commit,
      packageManager: rootManifest.packageManager,
      inputFingerprint: data.inputFingerprint,
      packageOrder: artifacts.map((item) => item.name),
      packages: artifacts,
    };
    await writeFile(
      join(artifactRoot, "manifest.json"),
      `${JSON.stringify(stable(manifest), null, 2)}\n`,
    );
    await command(bun, ["run", "check"]);
    await command(bun, ["run", "scripts/check-public-declarations.ts"]);
    await command(bun, ["run", "scripts/pack-and-smoke-exports.ts", "--artifacts", artifactRoot]);
    await command(bun, [
      "run",
      "scripts/pack-and-smoke-create-relkit.ts",
      "--artifacts",
      artifactRoot,
    ]);
    const notes = await format(releaseNotes(data), { parser: "markdown" });
    const notePath = join(root, "RELEASE_NOTES.md");
    if (writeNotes) await writeFile(notePath, notes, "utf8");
    else if (!readiness && (await readFile(notePath, "utf8")) !== notes)
      throw new Error("RELEASE_NOTES.md is stale; rerun with --write-notes and review the diff.");
    if (!temporary) {
      await writeFile(
        join(artifactRoot, "SHA256SUMS"),
        `${artifacts.map((item) => `${item.sha256}  ${item.file}`).join("\n")}\n`,
      );
      await writeFile(
        join(artifactRoot, "SHA512SUMS"),
        `${artifacts.map((item) => `${item.sha512}  ${item.file}`).join("\n")}\n`,
      );
      await copyFile(notePath, join(artifactRoot, "RELEASE_NOTES.md"));
    }
    if (!allowDirty) await assertClean(allow);
    console.log(
      JSON.stringify({
        protocol: "relkit.release-check",
        version,
        packages: items.length,
        artifacts: artifacts.length,
        templates: templates.length,
        inputFingerprint: data.inputFingerprint,
      }),
    );
  } finally {
    if (temporary) await rm(artifactRoot, { recursive: true, force: true });
  }
}

if (import.meta.main) await main();
