export default {
  plugins: ["@hughescr/stryker-bun-runner"],
  testRunner: "bun",
  coverageAnalysis: "perTest",
  reporters: ["clear-text", "json"],
  disableTypeChecks: false,
  ignorePatterns: [".relkit/**", "repos/effect/**"],
  mutate: [
    "packages/jobs/src/authorization.ts:24-83",
    "packages/jobs/src/duration.ts:37-72",
    "packages/jobs/src/task-policy-validation.ts:42-180",
    "packages/jobs/src/resolve-binding.ts:23-70",
    "packages/jobs/src/resolve-binding.ts:104-150",
    "packages/client/src/jobs/controller.ts:46-176",
    "packages/client/src/jobs/watch.ts:11-34",
    "packages/client/src/jobs/watch-feed-polling.ts:7-82",
  ],
  concurrency: 2,
  maxTestRunnerReuse: 50,
  tempDirName: "relkit-jobs-mutation",
  bun: {
    testFiles: [
      "packages/jobs/task-progress.test.ts",
      "packages/jobs/authorization-cursor.test.ts",
      "packages/jobs/client.test.ts",
      "packages/jobs/trigger-schedule.test.ts",
      "packages/jobs/authorization.test.ts",
      "packages/jobs/migration.test.ts",
      "packages/jobs/schedule-reconciliation.test.ts",
      "packages/jobs/task-policy.test.ts",
      "packages/jobs/identity.test.ts",
      "packages/jobs/authoring-boundaries.test.ts",
      "packages/jobs/task-wire.test.ts",
      "packages/jobs/resolve-binding.test.ts",
      "packages/jobs/boundary-policy.test.ts",
      "packages/jobs/jobs-quality.test.ts",
      "packages/client/jobs-watch.test.ts",
      "packages/client/jobs-watch-quality.test.ts",
      "packages/client/pending.test.ts",
    ],
    timeout: 30_000,
    inspectorTimeout: 10_000,
    smol: true,
    maxChildRss: 1_500_000_000,
  },
};
