export default {
  plugins: ["@stryker-mutator/vitest-runner"],
  testRunner: "vitest",
  coverageAnalysis: "perTest",
  reporters: ["clear-text", "json"],
  buildCommand: "bun scripts/jobs-coverage/link-sandbox-dependencies.ts",
  disableTypeChecks: false,
  // Local CodeGraph state includes a live daemon socket that cannot be copied.
  ignorePatterns: [".relkit", ".relkit-*", "repos/effect/**", "/.codegraph"],
  mutate: [
    "packages/jobs/src/authorization-grant.ts:20-42",
    "packages/jobs/src/authorization.ts:100-111",
    "packages/jobs/src/duration.ts:57-89",
    "packages/jobs/src/task-policy-value.ts:46-121",
    "packages/jobs/src/task-policy-value-copy.ts",
    "packages/jobs/src/resolve-binding.ts:23-70",
    "packages/jobs/src/resolve-binding.ts:104-150",
    "packages/client/src/jobs/controller.ts:56-91",
    "packages/client/src/jobs/controller.service.ts:90-142",
    "packages/client/src/jobs/controller.service.ts:145-182",
    "packages/client/src/jobs/controller.service.ts:201-246",
    "packages/client/src/jobs/feed-registry.service.ts:44-117",
    "packages/client/src/jobs/watch-feed-polling.ts:16-82",
    "packages/client/src/jobs/watch-feed-recovery.ts:19-35",
  ],
  concurrency: 6,
  symlinkNodeModules: false,
  maxTestRunnerReuse: 50,
  tempDirName: ".stryker-tmp",
  vitest: {
    configFile: "scripts/jobs-coverage/vitest.config.ts",
    related: false,
  },
};
