export default {
  plugins: ["@hughescr/stryker-bun-runner"],
  testRunner: "bun",
  coverageAnalysis: "perTest",
  reporters: ["clear-text", "json"],
  buildCommand: "bun scripts/jobs-coverage/link-sandbox-dependencies.ts",
  disableTypeChecks: false,
  // Local CodeGraph state includes a live daemon socket that cannot be copied.
  ignorePatterns: [".relkit", ".relkit-*", "repos/effect/**", "/.codegraph"],
  mutate: [
    "packages/jobs/src/authorization-grant.ts:20-42",
    "packages/jobs/src/authorization.ts:100-111",
    "packages/jobs/src/duration.ts:57-89",
    "packages/jobs/src/task-policy-value.ts:46-121",
    "packages/jobs/src/task-policy-value-copy.ts",
    "packages/jobs/src/resolve-binding.ts:23-70",
    "packages/jobs/src/resolve-binding.ts:104-150",
    "packages/client/src/jobs/controller.ts:46-176",
    "packages/client/src/jobs/watch.ts:11-34",
    "packages/client/src/jobs/watch-feed-polling.ts:7-82",
  ],
  concurrency: 6,
  symlinkNodeModules: false,
  maxTestRunnerReuse: 50,
  tempDirName: ".stryker-tmp",
  bun: {
    testFiles: [
      "packages/jobs/tests/task-progress.test.ts",
      "packages/jobs/tests/authorization-cursor.test.ts",
      "packages/jobs/tests/client.test.ts",
      "packages/jobs/tests/trigger-schedule.test.ts",
      "packages/jobs/tests/authorization.test.ts",
      "packages/jobs/tests/authorization-effect.test.ts",
      "packages/jobs/tests/migration.test.ts",
      "packages/jobs/tests/schedule-reconciliation.test.ts",
      "packages/jobs/tests/task-policy.test.ts",
      "packages/jobs/tests/identity.test.ts",
      "packages/jobs/tests/authoring-boundaries.test.ts",
      "packages/jobs/tests/task-wire.test.ts",
      "packages/jobs/tests/resolve-binding.test.ts",
      "packages/jobs/tests/boundary-policy.test.ts",
      "packages/jobs/tests/jobs-quality.test.ts",
      "packages/jobs/tests/trigger-boundaries.test.ts",
      "packages/jobs/tests/duration-effect.test.ts",
      "packages/client/jobs-watch.test.ts",
      "packages/client/jobs-watch-quality.test.ts",
      "packages/client/pending.test.ts",
    ],
    timeout: 30_000,
    inspectorTimeout: 10_000,
    smol: true,
    maxChildRss: 1_500_000_000,
  },
};
