/** Stable build-cohort and missing HTTP binding failures exposed by the runtime. */
export type RuntimeHonoManifestErrorCode =
  | "RELKIT_MANIFEST_VERSION_UNSUPPORTED"
  | "RELKIT_MANIFEST_GENERATOR_UNSUPPORTED"
  | "RELKIT_RUNTIME_INTEGRATION_PLAN_VERSION_UNSUPPORTED"
  | "RELKIT_RUNTIME_INTEGRATION_PLAN_REFERENCE_INVALID"
  | "RELKIT_RUNTIME_ACTIVATION_FINGERPRINT_INVALID"
  | "RELKIT_GRAPH_MANIFEST_MISMATCH"
  | "RELKIT_MANIFEST_MIDDLEWARE_MISSING"
  | "RELKIT_MANIFEST_MIDDLEWARE_MISMATCH"
  | "RELKIT_MANIFEST_RAW_ROUTE_MISSING"
  | "RELKIT_MANIFEST_TRANSFORM_MISSING";
